/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:09:54 GMT 2019
 */

package org.ow2.proactive.catalog.service.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.service.exception.AccessDeniedException;

public class AccessDeniedException_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AccessDeniedException accessDeniedException0 = new AccessDeniedException("The array of prefixes must not be null");
  }
}
