/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:04:03 GMT 2019
 */

package org.ow2.proactive.catalog.service.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.service.exception.DeleteNonEmptyBucketException;

public class DeleteNonEmptyBucketException_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DeleteNonEmptyBucketException deleteNonEmptyBucketException0 = new DeleteNonEmptyBucketException("void");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DeleteNonEmptyBucketException deleteNonEmptyBucketException0 = new DeleteNonEmptyBucketException((Throwable) null);
  }
}
