/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 14:59:20 GMT 2019
 */

package org.ow2.proactive.catalog.service.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.service.exception.NotAuthenticatedException;

public class NotAuthenticatedException_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NotAuthenticatedException notAuthenticatedException0 = new NotAuthenticatedException((String) null);
  }
}
