/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:08:36 GMT 2019
 */

package org.ow2.proactive.catalog.service.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import java.sql.SQLClientInfoException;
import org.ow2.proactive.catalog.service.exception.ParsingObjectException;

public class ParsingObjectException_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ParsingObjectException parsingObjectException0 = new ParsingObjectException("R)1_va~:x]c0Yw*'");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SQLClientInfoException sQLClientInfoException0 = new SQLClientInfoException();
      ParsingObjectException parsingObjectException0 = new ParsingObjectException("", sQLClientInfoException0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SQLClientInfoException sQLClientInfoException0 = new SQLClientInfoException();
      ParsingObjectException parsingObjectException0 = new ParsingObjectException(sQLClientInfoException0);
  }
}
