/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:00:28 GMT 2019
 */

package org.ow2.proactive.catalog.service.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.service.exception.PDFGenerationException;

public class PDFGenerationException_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PDFGenerationException pDFGenerationException0 = new PDFGenerationException((Throwable) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PDFGenerationException pDFGenerationException0 = new PDFGenerationException("3~TH|GVm");
  }
}
