/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:11:12 GMT 2019
 */

package org.ow2.proactive.catalog.service.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.service.exception.ResourceNotFoundException;

public class ResourceNotFoundException_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ResourceNotFoundException resourceNotFoundException0 = new ResourceNotFoundException("_vir|[J&e:&{G'AZ");
  }
}
