/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:11:01 GMT 2019
 */

package org.ow2.proactive.catalog.service.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.service.exception.RevisionNotFoundException;

public class RevisionNotFoundException_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RevisionNotFoundException revisionNotFoundException0 = new RevisionNotFoundException();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RevisionNotFoundException revisionNotFoundException0 = new RevisionNotFoundException("", "", 1L);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RevisionNotFoundException revisionNotFoundException0 = new RevisionNotFoundException("");
  }
}
