/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:01:47 GMT 2019
 */

package org.ow2.proactive.catalog.service.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.service.exception.UnprocessableEntityException;

public class UnprocessableEntityException_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UnprocessableEntityException unprocessableEntityException0 = new UnprocessableEntityException("Q-.5c");
      UnprocessableEntityException unprocessableEntityException1 = new UnprocessableEntityException(unprocessableEntityException0);
      assertFalse(unprocessableEntityException1.equals((Object)unprocessableEntityException0));
  }
}
