/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:06:19 GMT 2019
 */

package org.ow2.proactive.catalog.service.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.service.exception.WrongParametersException;

public class WrongParametersException_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WrongParametersException wrongParametersException0 = new WrongParametersException("Destination Locked");
      WrongParametersException wrongParametersException1 = new WrongParametersException(wrongParametersException0);
      assertFalse(wrongParametersException1.equals((Object)wrongParametersException0));
  }
}
