var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":54,"id":16432,"methods":[{"el":16,"sc":2,"sl":15},{"el":19,"sc":2,"sl":17},{"el":24,"sc":5,"sl":20},{"el":28,"sc":5,"sl":26},{"el":32,"sc":5,"sl":30},{"el":36,"sc":5,"sl":34},{"el":46,"sc":5,"sl":39},{"el":53,"sc":5,"sl":48}],"name":"ClassName","sl":11}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_1":{"methods":[{"sl":15},{"sl":20}],"name":"testDeleteUserAccount","pass":true,"statements":[{"sl":23}]},"test_20":{"methods":[{"sl":15},{"sl":20}],"name":"testDeleteUserAccountThatDoesNot","pass":true,"statements":[{"sl":23}]},"test_21":{"methods":[{"sl":15},{"sl":20}],"name":"testTransactionTwiceSameThread","pass":true,"statements":[{"sl":23}]},"test_27":{"methods":[{"sl":15},{"sl":20}],"name":"testStar","pass":true,"statements":[{"sl":23}]},"test_28":{"methods":[{"sl":15},{"sl":20}],"name":"testSingleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":23}]},"test_29":{"methods":[{"sl":15},{"sl":20}],"name":"testGetSessionFactory","pass":true,"statements":[{"sl":23}]},"test_47":{"methods":[{"sl":15},{"sl":20}],"name":"testCatchExceptionAndRollback","pass":true,"statements":[{"sl":23}]},"test_48":{"methods":[{"sl":15},{"sl":20}],"name":"testCreateUserAccountEmptyProfile","pass":true,"statements":[{"sl":23}]},"test_67":{"methods":[{"sl":15},{"sl":20}],"name":"testFindUserByUsername","pass":true,"statements":[{"sl":23}]},"test_73":{"methods":[{"sl":15},{"sl":20}],"name":"testMultipleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":23}]},"test_75":{"methods":[{"sl":15},{"sl":20}],"name":"testCatchRuntimeExceptionAndRollback","pass":true,"statements":[{"sl":23}]},"test_79":{"methods":[{"sl":15},{"sl":20}],"name":"testTransactionIsActive","pass":true,"statements":[{"sl":23}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [20, 28, 67, 1, 47, 48, 21, 27, 75, 29, 79, 73], [], [], [], [], [20, 28, 67, 1, 47, 48, 21, 27, 75, 29, 79, 73], [], [], [20, 28, 67, 1, 47, 48, 21, 27, 75, 29, 79, 73], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
