/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:37:49 GMT 2019
 */

package org.ow2.proactive.catalog.callgraph;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.callgraph.CallGraphHolderTest;

public class CallGraphHolderTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CallGraphHolderTest callGraphHolderTest0 = new CallGraphHolderTest();
  }
}
