/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 13:39:19 GMT 2019
 */

package org.ow2.proactive.catalog.callgraph;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.callgraph.CatalogObjectCallGraphPDFGenerator;

public class CatalogObjectCallGraphPDFGenerator_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CatalogObjectCallGraphPDFGenerator catalogObjectCallGraphPDFGenerator0 = new CatalogObjectCallGraphPDFGenerator();
  }
}
