/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 13:37:57 GMT 2019
 */

package org.ow2.proactive.catalog.callgraph;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.callgraph.GraphNode;

public class GraphNode_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      GraphNode graphNode0 = new GraphNode("", "", "", true);
      graphNode0.getObjectName();
      assertTrue(graphNode0.isInCatalog());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GraphNode graphNode0 = new GraphNode("", "", "", true);
      graphNode0.getObjectKind();
      assertTrue(graphNode0.isInCatalog());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GraphNode graphNode0 = new GraphNode("org.ow2.proactive.catalog.callgraph.GraphNode", "org.ow2.proactive.catalog.callgraph.GraphNode", "org.ow2.proactive.catalog.callgraph.GraphNode", true);
      boolean boolean0 = graphNode0.isInCatalog();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GraphNode.Builder graphNode_Builder0 = new GraphNode.Builder();
      GraphNode.Builder graphNode_Builder1 = graphNode_Builder0.bucketName("objectName");
      graphNode_Builder1.objectName("objectName");
      graphNode_Builder1.objectKind(")J?[nhE(kMrH_hx*O");
      GraphNode graphNode0 = graphNode_Builder0.build();
      graphNode0.hashCode();
      assertEquals(")J?[nhE(kMrH_hx*O", graphNode0.getObjectKind());
      assertEquals("objectName", graphNode0.getBucketName());
      assertEquals("objectName", graphNode0.getObjectName());
      assertFalse(graphNode0.isInCatalog());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      GraphNode.Builder graphNode_Builder0 = new GraphNode.Builder();
      GraphNode.Builder graphNode_Builder1 = graphNode_Builder0.bucketName("objectName");
      graphNode_Builder1.objectName("objectName");
      graphNode_Builder1.objectKind(")J?[nhE(kMrH_hx*O");
      GraphNode graphNode0 = graphNode_Builder0.build();
      String string0 = graphNode0.getBucketName();
      assertEquals(")J?[nhE(kMrH_hx*O", graphNode0.getObjectKind());
      assertFalse(graphNode0.isInCatalog());
      assertEquals("objectName", graphNode0.getObjectName());
      assertEquals("objectName", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      GraphNode.Builder graphNode_Builder0 = new GraphNode.Builder();
      GraphNode.Builder graphNode_Builder1 = graphNode_Builder0.isInCatalog(true);
      assertSame(graphNode_Builder0, graphNode_Builder1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GraphNode.Builder graphNode_Builder0 = new GraphNode.Builder();
      GraphNode.Builder graphNode_Builder1 = graphNode_Builder0.bucketName("objectName");
      graphNode_Builder1.objectName("objectName");
      graphNode_Builder1.objectKind(")J?[nhE(kMrH_hx*O");
      GraphNode graphNode0 = graphNode_Builder0.build();
      boolean boolean0 = graphNode0.equals("objectName");
      assertFalse(graphNode0.isInCatalog());
      assertEquals(")J?[nhE(kMrH_hx*O", graphNode0.getObjectKind());
      assertFalse(boolean0);
      assertEquals("objectName", graphNode0.getBucketName());
      assertEquals("objectName", graphNode0.getObjectName());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GraphNode.Builder graphNode_Builder0 = new GraphNode.Builder();
      GraphNode.Builder graphNode_Builder1 = graphNode_Builder0.bucketName("objectName");
      graphNode_Builder1.objectName("objectName");
      graphNode_Builder1.objectKind(")J?[nhE(kMrH_hx*O");
      GraphNode graphNode0 = graphNode_Builder0.build();
      boolean boolean0 = graphNode0.equals(graphNode0);
      assertTrue(boolean0);
      assertEquals("objectName", graphNode0.getObjectName());
      assertFalse(graphNode0.isInCatalog());
      assertEquals(")J?[nhE(kMrH_hx*O", graphNode0.getObjectKind());
      assertEquals("objectName", graphNode0.getBucketName());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GraphNode graphNode0 = new GraphNode("Dg:<]5FAV.eTr", "", "Dg:<]5FAV.eTr", true);
      boolean boolean0 = graphNode0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals("Dg:<]5FAV.eTr", graphNode0.getBucketName());
      assertTrue(graphNode0.isInCatalog());
      assertEquals("Dg:<]5FAV.eTr", graphNode0.getObjectKind());
      assertEquals("", graphNode0.getObjectName());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      GraphNode.Builder graphNode_Builder0 = new GraphNode.Builder();
      GraphNode.Builder graphNode_Builder1 = graphNode_Builder0.bucketName("objectName");
      GraphNode.Builder graphNode_Builder2 = graphNode_Builder1.objectName("objectName");
      graphNode_Builder1.objectKind(")J?[nhE(kMrH_hx*O");
      GraphNode graphNode0 = graphNode_Builder0.build();
      GraphNode graphNode1 = graphNode_Builder2.build();
      boolean boolean0 = graphNode1.equals(graphNode0);
      assertEquals("objectName", graphNode1.getObjectName());
      assertEquals("objectName", graphNode1.getBucketName());
      assertEquals(")J?[nhE(kMrH_hx*O", graphNode1.getObjectKind());
      assertFalse(graphNode1.isInCatalog());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GraphNode graphNode0 = new GraphNode("8CcS@!O59\"gZd4 ]3", "8CcS@!O59\"gZd4 ]3", "8CcS@!O59\"gZd4 ]3", false);
      GraphNode graphNode1 = new GraphNode("", "", "8CcS@!O59\"gZd4 ]3", false);
      boolean boolean0 = graphNode0.equals(graphNode1);
      assertEquals("", graphNode1.getBucketName());
      assertFalse(graphNode1.isInCatalog());
      assertEquals("", graphNode1.getObjectName());
      assertEquals("8CcS@!O59\"gZd4 ]3", graphNode1.getObjectKind());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      GraphNode graphNode0 = new GraphNode("7", "7", "7", false);
      GraphNode graphNode1 = new GraphNode("7", "", "", false);
      boolean boolean0 = graphNode0.equals(graphNode1);
      assertFalse(graphNode1.isInCatalog());
      assertEquals("7", graphNode1.getBucketName());
      assertEquals("", graphNode1.getObjectKind());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      GraphNode graphNode0 = null;
      try {
        graphNode0 = new GraphNode("1rd8", (String) null, "1rd8", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // objectName
         //
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      GraphNode graphNode0 = new GraphNode("", "", "", true);
      graphNode0.getBucketName();
      assertTrue(graphNode0.isInCatalog());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      GraphNode graphNode0 = new GraphNode("Dg:<]5FAV.eTr", "", "Dg:<]5FAV.eTr", true);
      String string0 = graphNode0.getObjectKind();
      assertEquals("Dg:<]5FAV.eTr", string0);
      assertEquals("Dg:<]5FAV.eTr", graphNode0.getBucketName());
      assertTrue(graphNode0.isInCatalog());
      assertEquals("", graphNode0.getObjectName());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      GraphNode.Builder graphNode_Builder0 = new GraphNode.Builder();
      GraphNode.Builder graphNode_Builder1 = graphNode_Builder0.bucketName("objectName");
      graphNode_Builder1.objectName("objectName");
      graphNode_Builder1.objectKind(")J?[nhE(kMrH_hx*O");
      GraphNode graphNode0 = graphNode_Builder0.build();
      String string0 = graphNode0.getObjectName();
      assertEquals(")J?[nhE(kMrH_hx*O", graphNode0.getObjectKind());
      assertFalse(graphNode0.isInCatalog());
      assertEquals("objectName", string0);
      assertEquals("objectName", graphNode0.getBucketName());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      GraphNode.Builder graphNode_Builder0 = new GraphNode.Builder();
      GraphNode.Builder graphNode_Builder1 = graphNode_Builder0.bucketName("");
      graphNode_Builder1.objectName("org.ow2.proactive.catalog.callgraph.GraphNode$Builder");
      graphNode_Builder0.objectKind("LdY7`]");
      GraphNode graphNode0 = graphNode_Builder1.build();
      boolean boolean0 = graphNode0.isInCatalog();
      assertEquals("LdY7`]", graphNode0.getObjectKind());
      assertEquals("org.ow2.proactive.catalog.callgraph.GraphNode$Builder", graphNode0.getObjectName());
      assertEquals("", graphNode0.getBucketName());
      assertFalse(boolean0);
  }
}
