/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 14:21:50 GMT 2019
 */

package org.ow2.proactive.catalog.report;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Optional;
import java.util.TreeSet;
import org.ow2.proactive.catalog.dto.CatalogObjectMetadata;
import org.ow2.proactive.catalog.report.CatalogObjectReportPDFGenerator;

public class CatalogObjectReportPDFGenerator_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CatalogObjectReportPDFGenerator catalogObjectReportPDFGenerator0 = new CatalogObjectReportPDFGenerator();
      TreeSet<CatalogObjectMetadata> treeSet0 = new TreeSet<CatalogObjectMetadata>();
      Optional<String> optional0 = Optional.empty();
      // Undeclared exception!
      try { 
        catalogObjectReportPDFGenerator0.generatePDF(treeSet0, optional0, optional0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Error while generating the PDF Report: org.evosuite.runtime.TooManyResourcesException: Loop has been executed more times than the allowed 10000
         //
      }
  }
}
