/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 14:46:58 GMT 2019
 */

package org.ow2.proactive.catalog.util.name.validator;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.util.name.validator.BucketNameValidator;

public class BucketNameValidator_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BucketNameValidator bucketNameValidator0 = new BucketNameValidator();
  }
}
