/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 14:47:04 GMT 2019
 */

package org.ow2.proactive.catalog.util.name.validator;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.util.name.validator.KindAndContentTypeValidator;

public class KindAndContentTypeValidator_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      KindAndContentTypeValidator kindAndContentTypeValidator0 = new KindAndContentTypeValidator();
  }
}
