/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 13:22:58 GMT 2019
 */

package org.ow2.proactive.catalog.graphql.bean.common;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.graphql.bean.common.Arguments;

public class Arguments_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Arguments arguments0 = Arguments.WHERE;
      String string0 = arguments0.getName();
      assertEquals("where", string0);
  }
}
