/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 13:25:13 GMT 2019
 */

package org.ow2.proactive.catalog.graphql.bean.common;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.graphql.bean.common.Fields;

public class Fields_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Fields fields0 = Fields.VALUE;
      String string0 = fields0.getName();
      assertEquals("value", string0);
  }
}
