/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:28:17 GMT 2019
 */

package org.ow2.proactive.catalog.rest.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.rest.controller.CatalogObjectCallGraphControllerTest;

public class CatalogObjectCallGraphControllerTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CatalogObjectCallGraphControllerTest catalogObjectCallGraphControllerTest0 = new CatalogObjectCallGraphControllerTest();
  }
}
