/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:33:12 GMT 2019
 */

package org.ow2.proactive.catalog.rest.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.rest.controller.CatalogObjectReportControllerTest;

public class CatalogObjectReportControllerTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CatalogObjectReportControllerTest catalogObjectReportControllerTest0 = new CatalogObjectReportControllerTest();
  }
}
