/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:34:19 GMT 2019
 */

package org.ow2.proactive.catalog.rest.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.rest.controller.SwaggerControllerTest;

public class SwaggerControllerTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SwaggerControllerTest swaggerControllerTest0 = new SwaggerControllerTest();
  }
}
