/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:38:56 GMT 2019
 */

package org.ow2.proactive.catalog.repository.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.repository.entity.BucketEntityTest;

public class BucketEntityTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BucketEntityTest bucketEntityTest0 = new BucketEntityTest();
  }
}
