/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:41:12 GMT 2019
 */

package org.ow2.proactive.catalog.repository.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.repository.entity.CatalogObjectRevisionEntityTest;

public class CatalogObjectRevisionEntityTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CatalogObjectRevisionEntityTest catalogObjectRevisionEntityTest0 = new CatalogObjectRevisionEntityTest();
  }
}
