/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 13:34:32 GMT 2019
 */

package org.ow2.proactive.catalog.graphql.bean.argument;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.graphql.bean.argument.CatalogObjectKindWhereArgs;

public class CatalogObjectKindWhereArgs_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0 = CatalogObjectKindWhereArgs.builder();
      CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder1 = catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0.like("");
      assertSame(catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder1, catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CatalogObjectKindWhereArgs catalogObjectKindWhereArgs0 = new CatalogObjectKindWhereArgs();
      catalogObjectKindWhereArgs0.hashCode();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CatalogObjectKindWhereArgs catalogObjectKindWhereArgs0 = new CatalogObjectKindWhereArgs();
      String string0 = catalogObjectKindWhereArgs0.toString();
      assertEquals("CatalogObjectKindWhereArgs()", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0 = new CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder();
      CatalogObjectKindWhereArgs catalogObjectKindWhereArgs0 = catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0.build();
      assertNull(catalogObjectKindWhereArgs0.getLike());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CatalogObjectKindWhereArgs catalogObjectKindWhereArgs0 = new CatalogObjectKindWhereArgs();
      CatalogObjectKindWhereArgs catalogObjectKindWhereArgs1 = new CatalogObjectKindWhereArgs();
      boolean boolean0 = catalogObjectKindWhereArgs0.equals(catalogObjectKindWhereArgs1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0 = new CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder();
      String string0 = catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0.toString();
      assertEquals("CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder(eq=null, ne=null, gt=null, gte=null, lt=null, lte=null, like=null, notLike=null)", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0 = new CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder();
      CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder1 = catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0.notLike("5EYOuE38I");
      assertSame(catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0, catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0 = new CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder();
      CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder1 = catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0.lt("I]");
      assertSame(catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0, catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0 = CatalogObjectKindWhereArgs.builder();
      CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder1 = catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0.gte(", notLike=");
      assertSame(catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0, catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0 = CatalogObjectKindWhereArgs.builder();
      CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder1 = catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0.gt("");
      assertSame(catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0, catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0 = new CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder();
      CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder1 = catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0.lte("");
      assertSame(catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder1, catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0 = new CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder();
      CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder1 = catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0.ne("I]");
      assertSame(catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0, catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0 = CatalogObjectKindWhereArgs.builder();
      CatalogObjectKindWhereArgs.CatalogObjectKindWhereArgsBuilder catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder1 = catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0.eq("");
      assertSame(catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder0, catalogObjectKindWhereArgs_CatalogObjectKindWhereArgsBuilder1);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CatalogObjectKindWhereArgs catalogObjectKindWhereArgs0 = new CatalogObjectKindWhereArgs();
      catalogObjectKindWhereArgs0.setLt("BYqm");
      CatalogObjectKindWhereArgs catalogObjectKindWhereArgs1 = new CatalogObjectKindWhereArgs();
      boolean boolean0 = catalogObjectKindWhereArgs1.equals(catalogObjectKindWhereArgs0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CatalogObjectKindWhereArgs catalogObjectKindWhereArgs0 = new CatalogObjectKindWhereArgs();
      boolean boolean0 = catalogObjectKindWhereArgs0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CatalogObjectKindWhereArgs catalogObjectKindWhereArgs0 = new CatalogObjectKindWhereArgs("r", "r", "r", "r", "r", "r", "r", "r");
      assertEquals("CatalogObjectKindWhereArgs()", catalogObjectKindWhereArgs0.toString());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CatalogObjectKindWhereArgs catalogObjectKindWhereArgs0 = new CatalogObjectKindWhereArgs();
      boolean boolean0 = catalogObjectKindWhereArgs0.canEqual((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CatalogObjectKindWhereArgs catalogObjectKindWhereArgs0 = new CatalogObjectKindWhereArgs();
      boolean boolean0 = catalogObjectKindWhereArgs0.canEqual(catalogObjectKindWhereArgs0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CatalogObjectKindWhereArgs catalogObjectKindWhereArgs0 = new CatalogObjectKindWhereArgs();
      boolean boolean0 = catalogObjectKindWhereArgs0.equals(catalogObjectKindWhereArgs0);
      assertTrue(boolean0);
  }
}
