/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 13:36:48 GMT 2019
 */

package org.ow2.proactive.catalog.graphql.bean.argument;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.graphql.bean.argument.CatalogObjectMetadataArgs;
import org.ow2.proactive.catalog.graphql.bean.argument.StringWhereArgs;

public class CatalogObjectMetadataArgs_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs("", ")", "3~UHly?YYlBBud1", "@Q{:':L(i\"", "3~UHly?YYlBBud1", (String) null, "@Q{:':L(i\"", "");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("", stringWhereArgs0);
      String string0 = catalogObjectMetadataArgs0.toString();
      assertEquals("CatalogObjectMetadataArgs(key=, value=StringWhereArgs(like=@Q{:':L(i\", notLike=))", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs("", ")", "3~UHly?YYlBBud1", "@Q{:':L(i\"", "3~UHly?YYlBBud1", (String) null, "@Q{:':L(i\"", "");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("", stringWhereArgs0);
      catalogObjectMetadataArgs0.hashCode();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs();
      catalogObjectMetadataArgs0.hashCode();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs("", ")", "3~UHly?YYlBBud1", "@Q{:':L(i\"", "3~UHly?YYlBBud1", (String) null, "@Q{:':L(i\"", "");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("", stringWhereArgs0);
      boolean boolean0 = catalogObjectMetadataArgs0.equals("CatalogObjectMetadataArgs(key=, value=StringWhereArgs(like=@Q{:':L(i\", notLike=))");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs();
      CatalogObjectMetadataArgs catalogObjectMetadataArgs1 = new CatalogObjectMetadataArgs();
      boolean boolean0 = catalogObjectMetadataArgs1.equals(catalogObjectMetadataArgs0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs();
      catalogObjectMetadataArgs0.setKey("O/ }yL!e/4;JXKs");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs1 = new CatalogObjectMetadataArgs();
      boolean boolean0 = catalogObjectMetadataArgs1.equals(catalogObjectMetadataArgs0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs();
      catalogObjectMetadataArgs0.setKey("O/ }yL!e/4;JXKs");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs1 = new CatalogObjectMetadataArgs();
      boolean boolean0 = catalogObjectMetadataArgs0.equals(catalogObjectMetadataArgs1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs("", ")", "3~UHly?YYlBBud1", "@Q{:':L(i\"", "3~UHly?YYlBBud1", (String) null, "@Q{:':L(i\"", "");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("", stringWhereArgs0);
      catalogObjectMetadataArgs0.setKey("CatalogObjectMetadataArgs(key=, value=StringWhereArgs(like=@Q{:':L(i\", notLike=))");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs1 = new CatalogObjectMetadataArgs("CatalogObjectMetadataArgs(key=, value=StringWhereArgs(like=@Q{:':L(i\", notLike=))", (StringWhereArgs) null);
      boolean boolean0 = catalogObjectMetadataArgs0.equals(catalogObjectMetadataArgs1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs("", ")", "3~UHly?YYlBBud1", "@Q{:':L(i\"", "3~UHly?YYlBBud1", (String) null, "@Q{:':L(i\"", "");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("", stringWhereArgs0);
      catalogObjectMetadataArgs0.setKey("CatalogObjectMetadataArgs(key=, value=StringWhereArgs(like=@Q{:':L(i\", notLike=))");
      catalogObjectMetadataArgs0.setValue((StringWhereArgs) null);
      CatalogObjectMetadataArgs catalogObjectMetadataArgs1 = new CatalogObjectMetadataArgs("CatalogObjectMetadataArgs(key=, value=StringWhereArgs(like=@Q{:':L(i\", notLike=))", (StringWhereArgs) null);
      assertTrue(catalogObjectMetadataArgs1.equals((Object)catalogObjectMetadataArgs0));
      
      catalogObjectMetadataArgs1.setValue(stringWhereArgs0);
      boolean boolean0 = catalogObjectMetadataArgs0.equals(catalogObjectMetadataArgs1);
      assertFalse(catalogObjectMetadataArgs1.equals((Object)catalogObjectMetadataArgs0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs("", ")", "3~UHly?YYlBBud1", "@Q{:':L(i\"", "3~UHly?YYlBBud1", (String) null, "@Q{:':L(i\"", "");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("", stringWhereArgs0);
      catalogObjectMetadataArgs0.setKey("CatalogObjectMetadataArgs(key=, value=StringWhereArgs(like=@Q{:':L(i\", notLike=))");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs1 = new CatalogObjectMetadataArgs("CatalogObjectMetadataArgs(key=, value=StringWhereArgs(like=@Q{:':L(i\", notLike=))", (StringWhereArgs) null);
      assertFalse(catalogObjectMetadataArgs1.equals((Object)catalogObjectMetadataArgs0));
      
      catalogObjectMetadataArgs1.setValue(stringWhereArgs0);
      boolean boolean0 = catalogObjectMetadataArgs0.equals(catalogObjectMetadataArgs1);
      assertTrue(catalogObjectMetadataArgs1.equals((Object)catalogObjectMetadataArgs0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs("", ")", "3~UHly?YYlBBud1", "@Q{:':L(i\"", "3~UHly?YYlBBud1", (String) null, "@Q{:':L(i\"", "");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("", stringWhereArgs0);
      StringWhereArgs stringWhereArgs1 = catalogObjectMetadataArgs0.getValue();
      assertEquals("", stringWhereArgs1.getNotLike());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs("", ")", "3~UHly?YYlBBud1", "@Q{:':L(i\"", "3~UHly?YYlBBud1", (String) null, "@Q{:':L(i\"", "");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("", stringWhereArgs0);
      String string0 = catalogObjectMetadataArgs0.getKey();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs("", ")", "3~UHly?YYlBBud1", "@Q{:':L(i\"", "3~UHly?YYlBBud1", (String) null, "@Q{:':L(i\"", "");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("", stringWhereArgs0);
      boolean boolean0 = catalogObjectMetadataArgs0.canEqual("CatalogObjectMetadataArgs(key=, value=StringWhereArgs(like=@Q{:':L(i\", notLike=))");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs("", ")", "3~UHly?YYlBBud1", "@Q{:':L(i\"", "3~UHly?YYlBBud1", (String) null, "@Q{:':L(i\"", "");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("", stringWhereArgs0);
      boolean boolean0 = catalogObjectMetadataArgs0.canEqual(catalogObjectMetadataArgs0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs("", ")", "3~UHly?YYlBBud1", "@Q{:':L(i\"", "3~UHly?YYlBBud1", (String) null, "@Q{:':L(i\"", "");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("", stringWhereArgs0);
      catalogObjectMetadataArgs0.setKey("CatalogObjectMetadataArgs(key=, value=StringWhereArgs(like=@Q{:':L(i\", notLike=))");
      String string0 = catalogObjectMetadataArgs0.getKey();
      assertEquals("CatalogObjectMetadataArgs(key=, value=StringWhereArgs(like=@Q{:':L(i\", notLike=))", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs((String) null, (String) null, "", "G\\&ztcs90", (String) null, (String) null, (String) null, "J=0m==/~E4n\"{|.!i");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs((String) null, stringWhereArgs0);
      String string0 = catalogObjectMetadataArgs0.getKey();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs("", ")", "3~UHly?YYlBBud1", "@Q{:':L(i\"", "3~UHly?YYlBBud1", (String) null, "@Q{:':L(i\"", "");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("", stringWhereArgs0);
      catalogObjectMetadataArgs0.setValue((StringWhereArgs) null);
      StringWhereArgs stringWhereArgs1 = catalogObjectMetadataArgs0.getValue();
      assertNull(stringWhereArgs1);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs();
      boolean boolean0 = catalogObjectMetadataArgs0.equals(catalogObjectMetadataArgs0);
      assertTrue(boolean0);
  }
}
