/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 13:27:29 GMT 2019
 */

package org.ow2.proactive.catalog.graphql.bean.argument;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.graphql.bean.argument.CatalogObjectNameWhereArgs;

public class CatalogObjectNameWhereArgs_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0 = CatalogObjectNameWhereArgs.builder();
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder1 = catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0.lte("CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder(eq=null, ne=null, gt=null, gte=null, lt=null, lte=null, like=null, notLike=null)");
      assertSame(catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder1, catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0 = CatalogObjectNameWhereArgs.builder();
      catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0.notLike(", lt=");
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs0 = new CatalogObjectNameWhereArgs();
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs1 = catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0.build();
      boolean boolean0 = catalogObjectNameWhereArgs1.equals(catalogObjectNameWhereArgs0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0 = CatalogObjectNameWhereArgs.builder();
      String string0 = catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0.toString();
      assertEquals("CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder(eq=null, ne=null, gt=null, gte=null, lt=null, lte=null, like=null, notLike=null)", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0 = CatalogObjectNameWhereArgs.builder();
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs0 = catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0.build();
      catalogObjectNameWhereArgs0.hashCode();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0 = CatalogObjectNameWhereArgs.builder();
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder1 = catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0.lt("");
      assertSame(catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder1, catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0 = CatalogObjectNameWhereArgs.builder();
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder1 = catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0.eq("StringWhereArgs(like=");
      assertSame(catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder1, catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0 = CatalogObjectNameWhereArgs.builder();
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder1 = catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0.gte(", lt=");
      assertSame(catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0, catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0 = CatalogObjectNameWhereArgs.builder();
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder1 = catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0.ne((String) null);
      assertSame(catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder1, catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0 = CatalogObjectNameWhereArgs.builder();
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder1 = catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0.gt("");
      assertSame(catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0, catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0 = CatalogObjectNameWhereArgs.builder();
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder1 = catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0.like("StringWhereArgs(like=");
      assertSame(catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0, catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs0 = new CatalogObjectNameWhereArgs();
      String string0 = catalogObjectNameWhereArgs0.toString();
      assertEquals("CatalogObjectNameWhereArgs()", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0 = CatalogObjectNameWhereArgs.builder();
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs0 = new CatalogObjectNameWhereArgs();
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs1 = catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0.build();
      boolean boolean0 = catalogObjectNameWhereArgs1.equals(catalogObjectNameWhereArgs0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0 = CatalogObjectNameWhereArgs.builder();
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs0 = catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0.build();
      boolean boolean0 = catalogObjectNameWhereArgs0.equals(", lt=");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs0 = new CatalogObjectNameWhereArgs("h<[gK.0Swu>", "h<[gK.0Swu>", "h<[gK.0Swu>", "h<[gK.0Swu>", "h<[gK.0Swu>", "h<[gK.0Swu>", "h<[gK.0Swu>", "h<[gK.0Swu>");
      assertEquals("CatalogObjectNameWhereArgs()", catalogObjectNameWhereArgs0.toString());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs0 = new CatalogObjectNameWhereArgs();
      boolean boolean0 = catalogObjectNameWhereArgs0.canEqual("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs0 = new CatalogObjectNameWhereArgs();
      boolean boolean0 = catalogObjectNameWhereArgs0.canEqual(catalogObjectNameWhereArgs0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder catalogObjectNameWhereArgs_CatalogObjectNameWhereArgsBuilder0 = new CatalogObjectNameWhereArgs.CatalogObjectNameWhereArgsBuilder();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs0 = new CatalogObjectNameWhereArgs();
      boolean boolean0 = catalogObjectNameWhereArgs0.equals(catalogObjectNameWhereArgs0);
      assertTrue(boolean0);
  }
}
