/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 13:33:24 GMT 2019
 */

package org.ow2.proactive.catalog.graphql.bean.argument;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.graphql.bean.argument.PageInfo;

public class PageInfo_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PageInfo pageInfo0 = new PageInfo();
      pageInfo0.setSize((-1));
      PageInfo pageInfo1 = new PageInfo();
      boolean boolean0 = pageInfo0.equals(pageInfo1);
      assertEquals((-1), pageInfo0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PageInfo pageInfo0 = new PageInfo();
      String string0 = pageInfo0.toString();
      assertEquals("PageInfo(page=0, size=0)", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PageInfo pageInfo0 = new PageInfo();
      PageInfo pageInfo1 = new PageInfo();
      boolean boolean0 = pageInfo0.equals(pageInfo1);
      assertTrue(boolean0);
      assertEquals(0, pageInfo1.getSize());
      assertEquals(0, pageInfo1.getPage());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PageInfo pageInfo0 = new PageInfo();
      Object object0 = new Object();
      boolean boolean0 = pageInfo0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PageInfo pageInfo0 = new PageInfo();
      PageInfo pageInfo1 = new PageInfo(913, 913);
      boolean boolean0 = pageInfo0.equals(pageInfo1);
      assertEquals(913, pageInfo1.getPage());
      assertEquals(913, pageInfo1.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PageInfo pageInfo0 = new PageInfo();
      int int0 = pageInfo0.getSize();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PageInfo pageInfo0 = new PageInfo();
      int int0 = pageInfo0.getPage();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PageInfo pageInfo0 = new PageInfo();
      Object object0 = new Object();
      boolean boolean0 = pageInfo0.canEqual(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PageInfo pageInfo0 = new PageInfo();
      boolean boolean0 = pageInfo0.canEqual(pageInfo0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PageInfo pageInfo0 = new PageInfo(0, 0);
      pageInfo0.setPage((-965));
      int int0 = pageInfo0.getPage();
      assertEquals((-965), int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PageInfo pageInfo0 = new PageInfo();
      pageInfo0.setPage(633);
      int int0 = pageInfo0.getPage();
      assertEquals(633, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PageInfo pageInfo0 = new PageInfo();
      pageInfo0.setSize((-3896));
      int int0 = pageInfo0.getSize();
      assertEquals((-3896), int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PageInfo pageInfo0 = new PageInfo(0, 0);
      assertEquals(0, pageInfo0.getSize());
      
      pageInfo0.setSize(1);
      int int0 = pageInfo0.getSize();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PageInfo pageInfo0 = new PageInfo();
      boolean boolean0 = pageInfo0.equals(pageInfo0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PageInfo pageInfo0 = new PageInfo();
      pageInfo0.setPage(633);
      PageInfo pageInfo1 = new PageInfo(0, 473);
      boolean boolean0 = pageInfo0.equals(pageInfo1);
      assertEquals(633, pageInfo0.getPage());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PageInfo pageInfo0 = new PageInfo(0, 0);
      assertEquals(0, pageInfo0.getSize());
      
      pageInfo0.setSize(1);
      PageInfo pageInfo1 = new PageInfo();
      boolean boolean0 = pageInfo0.equals(pageInfo1);
      assertEquals(1, pageInfo0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PageInfo pageInfo0 = new PageInfo();
      pageInfo0.setPage((-1));
      pageInfo0.hashCode();
      assertEquals((-1), pageInfo0.getPage());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PageInfo pageInfo0 = new PageInfo();
      pageInfo0.setSize(1);
      pageInfo0.hashCode();
      assertEquals(1, pageInfo0.getSize());
  }
}
