/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 13:29:54 GMT 2019
 */

package org.ow2.proactive.catalog.graphql.bean.argument;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.graphql.bean.argument.StringWhereArgs;

public class StringWhereArgs_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs(")", ")", ")", ")", ")", ")", ")", ")");
      String string0 = stringWhereArgs0.getLike();
      assertEquals(")", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs("IG<\"o:M)-0'~", "IG<\"o:M)-0'~", "IG<\"o:M)-0'~", "IG<\"o:M)-0'~", "IG<\"o:M)-0'~", "IG<\"o:M)-0'~", "IG<\"o:M)-0'~", "IG<\"o:M)-0'~");
      StringWhereArgs stringWhereArgs1 = new StringWhereArgs("IG<\"o:M)-0'~", "IG<\"o:M)-0'~", "IG<\"o:M)-0'~", "IG<\"o:M)-0'~", "IG<\"o:M)-0'~", "IG<\"o:M)-0'~", "IG<\"o:M)-0'~", "IG<\"o:M)-0'~");
      boolean boolean0 = stringWhereArgs0.equals(stringWhereArgs1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs();
      String string0 = stringWhereArgs0.toString();
      assertEquals("StringWhereArgs(like=null, notLike=null)", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs();
      boolean boolean0 = stringWhereArgs0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs();
      StringWhereArgs stringWhereArgs1 = new StringWhereArgs(")", ")", ")", ")", ")", ")", ")", ")");
      boolean boolean0 = stringWhereArgs0.equals(stringWhereArgs1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs();
      StringWhereArgs stringWhereArgs1 = new StringWhereArgs();
      boolean boolean0 = stringWhereArgs0.equals(stringWhereArgs1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs();
      StringWhereArgs stringWhereArgs1 = new StringWhereArgs();
      assertTrue(stringWhereArgs1.equals((Object)stringWhereArgs0));
      
      stringWhereArgs1.setLike("}");
      boolean boolean0 = stringWhereArgs0.equals(stringWhereArgs1);
      assertFalse(stringWhereArgs1.equals((Object)stringWhereArgs0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs();
      StringWhereArgs stringWhereArgs1 = new StringWhereArgs();
      assertTrue(stringWhereArgs1.equals((Object)stringWhereArgs0));
      
      stringWhereArgs1.setLike("");
      boolean boolean0 = stringWhereArgs1.equals(stringWhereArgs0);
      assertFalse(stringWhereArgs1.equals((Object)stringWhereArgs0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs();
      StringWhereArgs stringWhereArgs1 = new StringWhereArgs();
      assertTrue(stringWhereArgs1.equals((Object)stringWhereArgs0));
      
      stringWhereArgs1.setNotLike("v|bM]$p");
      boolean boolean0 = stringWhereArgs0.equals(stringWhereArgs1);
      assertFalse(stringWhereArgs1.equals((Object)stringWhereArgs0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs();
      stringWhereArgs0.notLike = ", lte=";
      StringWhereArgs stringWhereArgs1 = new StringWhereArgs();
      stringWhereArgs1.setLike(", lte=");
      stringWhereArgs0.like = ", lte=";
      boolean boolean0 = stringWhereArgs0.equals(stringWhereArgs1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs();
      String string0 = stringWhereArgs0.getNotLike();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs();
      String string0 = stringWhereArgs0.getLike();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs();
      boolean boolean0 = stringWhereArgs0.canEqual((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs();
      boolean boolean0 = stringWhereArgs0.canEqual(stringWhereArgs0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs();
      stringWhereArgs0.like = "";
      String string0 = stringWhereArgs0.getLike();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs((String) null, ").^ly", (String) null, "@!GCqknhtw~p&17/{", (String) null, "@!GCqknhtw~p&17/{", (String) null, "");
      String string0 = stringWhereArgs0.getNotLike();
      assertNotNull(string0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs();
      stringWhereArgs0.setNotLike(")");
      String string0 = stringWhereArgs0.getNotLike();
      assertEquals(")", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs();
      boolean boolean0 = stringWhereArgs0.equals(stringWhereArgs0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs();
      stringWhereArgs0.like = "";
      stringWhereArgs0.hashCode();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs("uKkh7nq (GyItem", "uKkh7nq (GyItem", "", "uKkh7nq (GyItem", (String) null, "", (String) null, "uKkh7nq (GyItem");
      stringWhereArgs0.ne = "uKkh7nq (GyItem";
      stringWhereArgs0.hashCode();
      assertEquals("uKkh7nq (GyItem", stringWhereArgs0.getNotLike());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs();
      stringWhereArgs0.setGte("");
      stringWhereArgs0.hashCode();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs("", ", gt=", "", "", "", "", "", "");
      stringWhereArgs0.hashCode();
      assertEquals("", stringWhereArgs0.getNotLike());
      assertEquals("", stringWhereArgs0.getLike());
  }
}
