var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":174,"id":4115,"methods":[{"el":34,"sc":2,"sl":29},{"el":39,"sc":5,"sl":36},{"el":44,"sc":5,"sl":41},{"el":49,"sc":5,"sl":46},{"el":56,"sc":5,"sl":52},{"el":61,"sc":5,"sl":58},{"el":66,"sc":5,"sl":63},{"el":71,"sc":5,"sl":68},{"el":76,"sc":5,"sl":73},{"el":81,"sc":5,"sl":78},{"el":86,"sc":5,"sl":83},{"el":91,"sc":5,"sl":88},{"el":96,"sc":5,"sl":93},{"el":101,"sc":5,"sl":98},{"el":106,"sc":5,"sl":103},{"el":111,"sc":5,"sl":108},{"el":116,"sc":5,"sl":113},{"el":121,"sc":5,"sl":118},{"el":126,"sc":5,"sl":123},{"el":131,"sc":5,"sl":128},{"el":136,"sc":5,"sl":133},{"el":141,"sc":5,"sl":138},{"el":146,"sc":5,"sl":143},{"el":151,"sc":5,"sl":148},{"el":157,"sc":5,"sl":153},{"el":162,"sc":5,"sl":159},{"el":167,"sc":5,"sl":164},{"el":172,"sc":5,"sl":169}],"name":"AssetPropertyTypeImpl","sl":12}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_1":{"methods":[{"sl":29}],"name":"testDeleteUserAccount","pass":true,"statements":[{"sl":33}]},"test_20":{"methods":[{"sl":29}],"name":"testDeleteUserAccountThatDoesNot","pass":true,"statements":[{"sl":33}]},"test_21":{"methods":[{"sl":29}],"name":"testTransactionTwiceSameThread","pass":true,"statements":[{"sl":33}]},"test_27":{"methods":[{"sl":29}],"name":"testStar","pass":true,"statements":[{"sl":33}]},"test_28":{"methods":[{"sl":29}],"name":"testSingleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":33}]},"test_29":{"methods":[{"sl":29}],"name":"testGetSessionFactory","pass":true,"statements":[{"sl":33}]},"test_47":{"methods":[{"sl":29}],"name":"testCatchExceptionAndRollback","pass":true,"statements":[{"sl":33}]},"test_48":{"methods":[{"sl":29}],"name":"testCreateUserAccountEmptyProfile","pass":true,"statements":[{"sl":33}]},"test_67":{"methods":[{"sl":29}],"name":"testFindUserByUsername","pass":true,"statements":[{"sl":33}]},"test_73":{"methods":[{"sl":29}],"name":"testMultipleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":33}]},"test_75":{"methods":[{"sl":29}],"name":"testCatchRuntimeExceptionAndRollback","pass":true,"statements":[{"sl":33}]},"test_79":{"methods":[{"sl":29}],"name":"testTransactionIsActive","pass":true,"statements":[{"sl":33}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [28, 67, 47, 48, 21, 29, 73, 20, 1, 27, 75, 79], [], [], [], [28, 67, 47, 48, 21, 29, 73, 20, 1, 27, 75, 79], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
