var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":139,"id":3954,"methods":[{"el":28,"sc":5,"sl":28},{"el":36,"sc":2,"sl":29},{"el":42,"sc":5,"sl":38},{"el":46,"sc":2,"sl":44},{"el":50,"sc":5,"sl":48},{"el":54,"sc":5,"sl":52},{"el":59,"sc":2,"sl":56},{"el":63,"sc":2,"sl":61},{"el":67,"sc":2,"sl":65},{"el":71,"sc":2,"sl":69},{"el":75,"sc":2,"sl":73},{"el":79,"sc":2,"sl":77},{"el":83,"sc":2,"sl":81},{"el":87,"sc":2,"sl":85},{"el":91,"sc":2,"sl":89},{"el":96,"sc":5,"sl":93},{"el":100,"sc":2,"sl":98},{"el":105,"sc":5,"sl":102},{"el":109,"sc":2,"sl":107},{"el":115,"sc":2,"sl":111},{"el":119,"sc":5,"sl":117},{"el":125,"sc":5,"sl":122},{"el":130,"sc":5,"sl":127},{"el":138,"sc":2,"sl":132}],"name":"AssetListItem","sl":12}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_1":{"methods":[{"sl":28},{"sl":38}],"name":"testDeleteUserAccount","pass":true,"statements":[{"sl":41}]},"test_20":{"methods":[{"sl":28},{"sl":38}],"name":"testDeleteUserAccountThatDoesNot","pass":true,"statements":[{"sl":41}]},"test_21":{"methods":[{"sl":28},{"sl":38}],"name":"testTransactionTwiceSameThread","pass":true,"statements":[{"sl":41}]},"test_27":{"methods":[{"sl":28},{"sl":38}],"name":"testStar","pass":true,"statements":[{"sl":41}]},"test_28":{"methods":[{"sl":28},{"sl":38}],"name":"testSingleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":41}]},"test_29":{"methods":[{"sl":28},{"sl":38}],"name":"testGetSessionFactory","pass":true,"statements":[{"sl":41}]},"test_47":{"methods":[{"sl":28},{"sl":38}],"name":"testCatchExceptionAndRollback","pass":true,"statements":[{"sl":41}]},"test_48":{"methods":[{"sl":28},{"sl":38}],"name":"testCreateUserAccountEmptyProfile","pass":true,"statements":[{"sl":41}]},"test_67":{"methods":[{"sl":28},{"sl":38}],"name":"testFindUserByUsername","pass":true,"statements":[{"sl":41}]},"test_73":{"methods":[{"sl":28},{"sl":38}],"name":"testMultipleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":41}]},"test_75":{"methods":[{"sl":28},{"sl":38}],"name":"testCatchRuntimeExceptionAndRollback","pass":true,"statements":[{"sl":41}]},"test_79":{"methods":[{"sl":28},{"sl":38}],"name":"testTransactionIsActive","pass":true,"statements":[{"sl":41}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [20, 28, 67, 1, 47, 48, 21, 27, 75, 29, 79, 73], [], [], [], [], [], [], [], [], [], [20, 28, 67, 1, 47, 48, 21, 27, 75, 29, 79, 73], [], [], [20, 28, 67, 1, 47, 48, 21, 27, 75, 29, 79, 73], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
