var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":87,"id":4640,"methods":[{"el":24,"sc":2,"sl":20},{"el":27,"sc":2,"sl":25},{"el":31,"sc":5,"sl":29},{"el":35,"sc":5,"sl":33},{"el":40,"sc":5,"sl":37},{"el":43,"sc":5,"sl":41},{"el":48,"sc":5,"sl":45},{"el":51,"sc":5,"sl":49},{"el":55,"sc":2,"sl":53},{"el":58,"sc":2,"sl":56},{"el":62,"sc":2,"sl":60},{"el":65,"sc":2,"sl":63},{"el":69,"sc":2,"sl":67},{"el":72,"sc":2,"sl":70},{"el":76,"sc":2,"sl":74},{"el":79,"sc":2,"sl":77},{"el":83,"sc":2,"sl":81},{"el":86,"sc":2,"sl":84}],"name":"AuthenticationTicket","sl":8}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_1":{"methods":[{"sl":20}],"name":"testDeleteUserAccount","pass":true,"statements":[{"sl":23}]},"test_20":{"methods":[{"sl":20}],"name":"testDeleteUserAccountThatDoesNot","pass":true,"statements":[{"sl":23}]},"test_21":{"methods":[{"sl":20}],"name":"testTransactionTwiceSameThread","pass":true,"statements":[{"sl":23}]},"test_27":{"methods":[{"sl":20}],"name":"testStar","pass":true,"statements":[{"sl":23}]},"test_28":{"methods":[{"sl":20}],"name":"testSingleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":23}]},"test_29":{"methods":[{"sl":20}],"name":"testGetSessionFactory","pass":true,"statements":[{"sl":23}]},"test_47":{"methods":[{"sl":20}],"name":"testCatchExceptionAndRollback","pass":true,"statements":[{"sl":23}]},"test_48":{"methods":[{"sl":20}],"name":"testCreateUserAccountEmptyProfile","pass":true,"statements":[{"sl":23}]},"test_67":{"methods":[{"sl":20}],"name":"testFindUserByUsername","pass":true,"statements":[{"sl":23}]},"test_73":{"methods":[{"sl":20}],"name":"testMultipleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":23}]},"test_75":{"methods":[{"sl":20}],"name":"testCatchRuntimeExceptionAndRollback","pass":true,"statements":[{"sl":23}]},"test_79":{"methods":[{"sl":20}],"name":"testTransactionIsActive","pass":true,"statements":[{"sl":23}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [20, 28, 67, 1, 47, 48, 21, 27, 75, 29, 79, 73], [], [], [20, 28, 67, 1, 47, 48, 21, 27, 75, 29, 79, 73], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
