var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":84,"id":4985,"methods":[{"el":23,"sc":5,"sl":18},{"el":27,"sc":2,"sl":25},{"el":32,"sc":5,"sl":29},{"el":37,"sc":5,"sl":34},{"el":43,"sc":5,"sl":39},{"el":47,"sc":5,"sl":45},{"el":52,"sc":5,"sl":49},{"el":56,"sc":5,"sl":54},{"el":61,"sc":5,"sl":58},{"el":65,"sc":5,"sl":63},{"el":70,"sc":5,"sl":67},{"el":74,"sc":5,"sl":72},{"el":79,"sc":5,"sl":76},{"el":83,"sc":5,"sl":81}],"name":"ChangelogImpl","sl":9}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_1":{"methods":[{"sl":18}],"name":"testDeleteUserAccount","pass":true,"statements":[{"sl":22}]},"test_20":{"methods":[{"sl":18}],"name":"testDeleteUserAccountThatDoesNot","pass":true,"statements":[{"sl":22}]},"test_21":{"methods":[{"sl":18}],"name":"testTransactionTwiceSameThread","pass":true,"statements":[{"sl":22}]},"test_27":{"methods":[{"sl":18}],"name":"testStar","pass":true,"statements":[{"sl":22}]},"test_28":{"methods":[{"sl":18}],"name":"testSingleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":22}]},"test_29":{"methods":[{"sl":18}],"name":"testGetSessionFactory","pass":true,"statements":[{"sl":22}]},"test_47":{"methods":[{"sl":18}],"name":"testCatchExceptionAndRollback","pass":true,"statements":[{"sl":22}]},"test_48":{"methods":[{"sl":18}],"name":"testCreateUserAccountEmptyProfile","pass":true,"statements":[{"sl":22}]},"test_67":{"methods":[{"sl":18}],"name":"testFindUserByUsername","pass":true,"statements":[{"sl":22}]},"test_73":{"methods":[{"sl":18}],"name":"testMultipleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":22}]},"test_75":{"methods":[{"sl":18}],"name":"testCatchRuntimeExceptionAndRollback","pass":true,"statements":[{"sl":22}]},"test_79":{"methods":[{"sl":18}],"name":"testTransactionIsActive","pass":true,"statements":[{"sl":22}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [20, 28, 67, 1, 47, 48, 21, 27, 75, 29, 79, 73], [], [], [], [20, 28, 67, 1, 47, 48, 21, 27, 75, 29, 79, 73], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
