var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":88,"id":5260,"methods":[{"el":32,"sc":5,"sl":28},{"el":35,"sc":5,"sl":33},{"el":40,"sc":5,"sl":37},{"el":45,"sc":5,"sl":42},{"el":50,"sc":5,"sl":47},{"el":54,"sc":5,"sl":52},{"el":60,"sc":5,"sl":56},{"el":65,"sc":5,"sl":62},{"el":71,"sc":5,"sl":67},{"el":76,"sc":5,"sl":73},{"el":82,"sc":5,"sl":78},{"el":87,"sc":5,"sl":84}],"name":"CustomerGroupMembershipImpl","sl":17}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_1":{"methods":[{"sl":28}],"name":"testDeleteUserAccount","pass":true,"statements":[{"sl":31}]},"test_20":{"methods":[{"sl":28}],"name":"testDeleteUserAccountThatDoesNot","pass":true,"statements":[{"sl":31}]},"test_21":{"methods":[{"sl":28}],"name":"testTransactionTwiceSameThread","pass":true,"statements":[{"sl":31}]},"test_27":{"methods":[{"sl":28}],"name":"testStar","pass":true,"statements":[{"sl":31}]},"test_28":{"methods":[{"sl":28}],"name":"testSingleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":31}]},"test_29":{"methods":[{"sl":28}],"name":"testGetSessionFactory","pass":true,"statements":[{"sl":31}]},"test_47":{"methods":[{"sl":28}],"name":"testCatchExceptionAndRollback","pass":true,"statements":[{"sl":31}]},"test_48":{"methods":[{"sl":28}],"name":"testCreateUserAccountEmptyProfile","pass":true,"statements":[{"sl":31}]},"test_67":{"methods":[{"sl":28}],"name":"testFindUserByUsername","pass":true,"statements":[{"sl":31}]},"test_73":{"methods":[{"sl":28}],"name":"testMultipleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":31}]},"test_75":{"methods":[{"sl":28}],"name":"testCatchRuntimeExceptionAndRollback","pass":true,"statements":[{"sl":31}]},"test_79":{"methods":[{"sl":28}],"name":"testTransactionIsActive","pass":true,"statements":[{"sl":31}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [20, 28, 67, 1, 47, 48, 21, 27, 75, 29, 79, 73], [], [], [20, 28, 67, 1, 47, 48, 21, 27, 75, 29, 79, 73], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
