var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":58,"id":7191,"methods":[{"el":20,"sc":2,"sl":16},{"el":23,"sc":2,"sl":21},{"el":28,"sc":2,"sl":25},{"el":31,"sc":2,"sl":29},{"el":36,"sc":2,"sl":33},{"el":39,"sc":2,"sl":37},{"el":44,"sc":2,"sl":41},{"el":47,"sc":2,"sl":45},{"el":52,"sc":2,"sl":49},{"el":55,"sc":2,"sl":53}],"name":"HistoryFilterRelation","sl":7}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_1":{"methods":[{"sl":16}],"name":"testDeleteUserAccount","pass":true,"statements":[{"sl":19}]},"test_20":{"methods":[{"sl":16}],"name":"testDeleteUserAccountThatDoesNot","pass":true,"statements":[{"sl":19}]},"test_21":{"methods":[{"sl":16}],"name":"testTransactionTwiceSameThread","pass":true,"statements":[{"sl":19}]},"test_27":{"methods":[{"sl":16}],"name":"testStar","pass":true,"statements":[{"sl":19}]},"test_28":{"methods":[{"sl":16}],"name":"testSingleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":19}]},"test_29":{"methods":[{"sl":16}],"name":"testGetSessionFactory","pass":true,"statements":[{"sl":19}]},"test_47":{"methods":[{"sl":16}],"name":"testCatchExceptionAndRollback","pass":true,"statements":[{"sl":19}]},"test_48":{"methods":[{"sl":16}],"name":"testCreateUserAccountEmptyProfile","pass":true,"statements":[{"sl":19}]},"test_67":{"methods":[{"sl":16}],"name":"testFindUserByUsername","pass":true,"statements":[{"sl":19}]},"test_73":{"methods":[{"sl":16}],"name":"testMultipleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":19}]},"test_75":{"methods":[{"sl":16}],"name":"testCatchRuntimeExceptionAndRollback","pass":true,"statements":[{"sl":19}]},"test_79":{"methods":[{"sl":16}],"name":"testTransactionIsActive","pass":true,"statements":[{"sl":19}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [28, 67, 47, 48, 21, 29, 73, 20, 1, 27, 75, 79], [], [], [28, 67, 47, 48, 21, 29, 73, 20, 1, 27, 75, 79], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
