var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":111,"id":10260,"methods":[{"el":35,"sc":5,"sl":31},{"el":38,"sc":5,"sl":36},{"el":43,"sc":5,"sl":40},{"el":48,"sc":5,"sl":45},{"el":53,"sc":5,"sl":50},{"el":56,"sc":5,"sl":54},{"el":61,"sc":5,"sl":58},{"el":65,"sc":5,"sl":63},{"el":71,"sc":5,"sl":67},{"el":75,"sc":5,"sl":73},{"el":81,"sc":5,"sl":77},{"el":84,"sc":5,"sl":82},{"el":90,"sc":5,"sl":86},{"el":93,"sc":5,"sl":91},{"el":107,"sc":5,"sl":95},{"el":110,"sc":5,"sl":108}],"name":"UserGroupImpl","sl":18}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_1":{"methods":[{"sl":31}],"name":"testDeleteUserAccount","pass":true,"statements":[{"sl":34}]},"test_20":{"methods":[{"sl":31}],"name":"testDeleteUserAccountThatDoesNot","pass":true,"statements":[{"sl":34}]},"test_21":{"methods":[{"sl":31}],"name":"testTransactionTwiceSameThread","pass":true,"statements":[{"sl":34}]},"test_27":{"methods":[{"sl":31}],"name":"testStar","pass":true,"statements":[{"sl":34}]},"test_28":{"methods":[{"sl":31}],"name":"testSingleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":34}]},"test_29":{"methods":[{"sl":31}],"name":"testGetSessionFactory","pass":true,"statements":[{"sl":34}]},"test_47":{"methods":[{"sl":31}],"name":"testCatchExceptionAndRollback","pass":true,"statements":[{"sl":34}]},"test_48":{"methods":[{"sl":31}],"name":"testCreateUserAccountEmptyProfile","pass":true,"statements":[{"sl":34}]},"test_67":{"methods":[{"sl":31}],"name":"testFindUserByUsername","pass":true,"statements":[{"sl":34}]},"test_73":{"methods":[{"sl":31}],"name":"testMultipleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":34}]},"test_75":{"methods":[{"sl":31}],"name":"testCatchRuntimeExceptionAndRollback","pass":true,"statements":[{"sl":34}]},"test_79":{"methods":[{"sl":31}],"name":"testTransactionIsActive","pass":true,"statements":[{"sl":34}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [20, 28, 67, 1, 47, 48, 21, 27, 75, 29, 79, 73], [], [], [20, 28, 67, 1, 47, 48, 21, 27, 75, 29, 79, 73], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
