/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:26:01 GMT 2019
 */

package org.ow2.proactive.catalog.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.dto.BucketMetadataTest;

public class BucketMetadataTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BucketMetadataTest bucketMetadataTest0 = new BucketMetadataTest();
  }
}
