/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 12:53:01 GMT 2019
 */

package org.ow2.proactive.catalog.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedHashSet;
import org.ow2.proactive.catalog.dto.BucketMetadata;
import org.ow2.proactive.catalog.repository.entity.BucketEntity;
import org.ow2.proactive.catalog.repository.entity.CatalogObjectEntity;

public class BucketMetadata_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BucketMetadata bucketMetadata0 = null;
      try {
        bucketMetadata0 = new BucketMetadata((BucketEntity) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BucketEntity bucketEntity0 = new BucketEntity();
      BucketMetadata bucketMetadata0 = new BucketMetadata(bucketEntity0);
      bucketMetadata0.hashCode();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BucketEntity bucketEntity0 = new BucketEntity();
      BucketMetadata bucketMetadata0 = new BucketMetadata(bucketEntity0);
      String string0 = bucketMetadata0.toString();
      assertEquals("BucketMetadata(owner=null, name=null)", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BucketEntity bucketEntity0 = new BucketEntity();
      BucketMetadata bucketMetadata0 = new BucketMetadata(bucketEntity0);
      boolean boolean0 = bucketMetadata0.equals("BucketMetadata(owner=null, name=null)");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BucketEntity bucketEntity0 = new BucketEntity();
      BucketMetadata bucketMetadata0 = new BucketMetadata(bucketEntity0);
      boolean boolean0 = bucketMetadata0.equals(bucketMetadata0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BucketMetadata bucketMetadata0 = new BucketMetadata("', '", (String) null);
      boolean boolean0 = bucketMetadata0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BucketEntity bucketEntity0 = new BucketEntity();
      BucketMetadata bucketMetadata0 = new BucketMetadata(bucketEntity0);
      BucketMetadata bucketMetadata1 = new BucketMetadata(bucketEntity0);
      boolean boolean0 = bucketMetadata0.equals(bucketMetadata1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BucketMetadata bucketMetadata0 = new BucketMetadata("", "");
      String string0 = bucketMetadata0.getOwner();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BucketEntity bucketEntity0 = new BucketEntity();
      BucketMetadata bucketMetadata0 = new BucketMetadata(bucketEntity0);
      String string0 = bucketMetadata0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BucketMetadata bucketMetadata0 = new BucketMetadata("", "");
      String string0 = bucketMetadata0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BucketMetadata bucketMetadata0 = new BucketMetadata("BucketMetadata(owner=null, name=null)", (String) null);
      String string0 = bucketMetadata0.getName();
      assertEquals("BucketMetadata(owner=null, name=null)", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Long long0 = new Long(0L);
      LinkedHashSet<CatalogObjectEntity> linkedHashSet0 = new LinkedHashSet<CatalogObjectEntity>(1);
      BucketEntity bucketEntity0 = new BucketEntity(long0, "com.google.common.base.Predicates$ContainsPatternFromStringPredicate", "com.google.common.base.Predicates$ContainsPatternFromStringPredicate", linkedHashSet0);
      BucketMetadata bucketMetadata0 = new BucketMetadata(bucketEntity0);
      String string0 = bucketMetadata0.getOwner();
      assertEquals("com.google.common.base.Predicates$ContainsPatternFromStringPredicate", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      BucketMetadata bucketMetadata0 = new BucketMetadata((String) null, (String) null);
      String string0 = bucketMetadata0.getOwner();
      assertNull(string0);
  }
}
