/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 12:56:28 GMT 2019
 */

package org.ow2.proactive.catalog.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.dto.CatalogObjectNameReference;

public class CatalogObjectNameReference_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference((String) null, (String) null);
      String string0 = catalogObjectNameReference0.toString();
      assertEquals("CatalogObjectNameReference(bucketName=null, name=null)", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference((String) null, (String) null);
      catalogObjectNameReference0.hashCode();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference((String) null, (String) null);
      boolean boolean0 = catalogObjectNameReference0.equals(catalogObjectNameReference0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference((String) null, (String) null);
      boolean boolean0 = catalogObjectNameReference0.equals("CatalogObjectNameReference(bucketName=1Wj@=Z?o;?g, name=At-Xfe`E&)");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference((String) null, (String) null);
      CatalogObjectNameReference catalogObjectNameReference1 = new CatalogObjectNameReference((String) null, (String) null);
      boolean boolean0 = catalogObjectNameReference0.equals(catalogObjectNameReference1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference((String) null, (String) null);
      CatalogObjectNameReference catalogObjectNameReference1 = new CatalogObjectNameReference("1Wj@=Z?o;?g", "At-Xfe`E&");
      boolean boolean0 = catalogObjectNameReference0.equals(catalogObjectNameReference1);
      assertEquals("At-Xfe`E&", catalogObjectNameReference1.getName());
      assertEquals("1Wj@=Z?o;?g", catalogObjectNameReference1.getBucketName());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference("", "");
      CatalogObjectNameReference catalogObjectNameReference1 = new CatalogObjectNameReference("CatalogObjectNameReference(bucketName=, name=)", "g<l]r=I#hyvt)sT");
      boolean boolean0 = catalogObjectNameReference0.equals(catalogObjectNameReference1);
      assertEquals("CatalogObjectNameReference(bucketName=, name=)", catalogObjectNameReference1.getBucketName());
      assertFalse(boolean0);
      assertEquals("g<l]r=I#hyvt)sT", catalogObjectNameReference1.getName());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference((String) null, (String) null);
      CatalogObjectNameReference catalogObjectNameReference1 = new CatalogObjectNameReference((String) null, "CatalogObjectNameReference(bucketName=null, name=null)");
      boolean boolean0 = catalogObjectNameReference0.equals(catalogObjectNameReference1);
      assertFalse(boolean0);
      assertFalse(catalogObjectNameReference1.equals((Object)catalogObjectNameReference0));
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference("", "");
      CatalogObjectNameReference catalogObjectNameReference1 = new CatalogObjectNameReference("", "");
      boolean boolean0 = catalogObjectNameReference0.equals(catalogObjectNameReference1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference((String) null, (String) null);
      String string0 = catalogObjectNameReference0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference((String) null, (String) null);
      String string0 = catalogObjectNameReference0.getBucketName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference("", "");
      boolean boolean0 = catalogObjectNameReference0.canEqual("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference("V}nO4?R6i'z:^,", "`2|^-}Zu21");
      catalogObjectNameReference0.canEqual(catalogObjectNameReference0);
      assertEquals("`2|^-}Zu21", catalogObjectNameReference0.getName());
      assertEquals("V}nO4?R6i'z:^,", catalogObjectNameReference0.getBucketName());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference("", "");
      String string0 = catalogObjectNameReference0.getBucketName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference("1Wj@=Z?o;?g", "At-Xfe`E&");
      String string0 = catalogObjectNameReference0.getBucketName();
      assertEquals("1Wj@=Z?o;?g", string0);
      assertEquals("At-Xfe`E&", catalogObjectNameReference0.getName());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference("", "");
      String string0 = catalogObjectNameReference0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference("1Wj@=Z?o;?g", "At-Xfe`E&");
      String string0 = catalogObjectNameReference0.getName();
      assertEquals("1Wj@=Z?o;?g", catalogObjectNameReference0.getBucketName());
      assertEquals("At-Xfe`E&", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference("WRU[E_aN+Y", "WRU[E_aN+Y");
      CatalogObjectNameReference catalogObjectNameReference1 = new CatalogObjectNameReference("WRU[E_aN+Y", (String) null);
      boolean boolean0 = catalogObjectNameReference1.equals(catalogObjectNameReference0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference("CatalogObjectNameReference(bucketName=, name=)", "g<l]r=I#hyvt)sT");
      CatalogObjectNameReference catalogObjectNameReference1 = new CatalogObjectNameReference("CatalogObjectNameReference(bucketName=, name=)", "");
      boolean boolean0 = catalogObjectNameReference0.equals(catalogObjectNameReference1);
      assertFalse(boolean0);
      assertEquals("CatalogObjectNameReference(bucketName=, name=)", catalogObjectNameReference1.getBucketName());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CatalogObjectNameReference catalogObjectNameReference0 = new CatalogObjectNameReference("", "");
      catalogObjectNameReference0.hashCode();
  }
}
