/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 12:55:19 GMT 2019
 */

package org.ow2.proactive.catalog.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Stack;
import java.util.Vector;
import org.ow2.proactive.catalog.dto.CatalogObjectMetadata;
import org.ow2.proactive.catalog.dto.CatalogObjectMetadataList;
import org.ow2.proactive.catalog.dto.Metadata;

public class CatalogObjectMetadataList_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CatalogObjectMetadataList catalogObjectMetadataList0 = new CatalogObjectMetadataList((List<CatalogObjectMetadata>) null);
      CatalogObjectMetadataList catalogObjectMetadataList1 = new CatalogObjectMetadataList((List<CatalogObjectMetadata>) null);
      boolean boolean0 = catalogObjectMetadataList0.equals(catalogObjectMetadataList1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CatalogObjectMetadataList catalogObjectMetadataList0 = new CatalogObjectMetadataList((List<CatalogObjectMetadata>) null);
      String string0 = catalogObjectMetadataList0.toString();
      assertEquals("CatalogObjectMetadataList(objectMetadataList=null)", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Stack<Metadata> stack0 = new Stack<Metadata>();
      CatalogObjectMetadata catalogObjectMetadata0 = new CatalogObjectMetadata("fK<_U3p[z6=", "", "", "", 260L, "3O`UUM[4=#", "CatalogObjectMetadataList(objectMetadataList=null)", stack0, "BloomFilters must have the same size underlying bit arrays (%s != %s)");
      CatalogObjectMetadataList catalogObjectMetadataList0 = new CatalogObjectMetadataList(catalogObjectMetadata0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ArrayList<CatalogObjectMetadata> arrayList0 = new ArrayList<CatalogObjectMetadata>();
      CatalogObjectMetadataList catalogObjectMetadataList0 = new CatalogObjectMetadataList(arrayList0);
      catalogObjectMetadataList0.hashCode();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CatalogObjectMetadataList catalogObjectMetadataList0 = new CatalogObjectMetadataList((List<CatalogObjectMetadata>) null);
      catalogObjectMetadataList0.hashCode();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ArrayList<CatalogObjectMetadata> arrayList0 = new ArrayList<CatalogObjectMetadata>();
      CatalogObjectMetadataList catalogObjectMetadataList0 = new CatalogObjectMetadataList(arrayList0);
      Object object0 = new Object();
      boolean boolean0 = catalogObjectMetadataList0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ArrayList<CatalogObjectMetadata> arrayList0 = new ArrayList<CatalogObjectMetadata>();
      CatalogObjectMetadataList catalogObjectMetadataList0 = new CatalogObjectMetadataList((List<CatalogObjectMetadata>) null);
      CatalogObjectMetadataList catalogObjectMetadataList1 = new CatalogObjectMetadataList(arrayList0);
      boolean boolean0 = catalogObjectMetadataList1.equals(catalogObjectMetadataList0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ArrayList<CatalogObjectMetadata> arrayList0 = new ArrayList<CatalogObjectMetadata>();
      CatalogObjectMetadataList catalogObjectMetadataList0 = new CatalogObjectMetadataList((List<CatalogObjectMetadata>) null);
      CatalogObjectMetadataList catalogObjectMetadataList1 = new CatalogObjectMetadataList(arrayList0);
      boolean boolean0 = catalogObjectMetadataList0.equals(catalogObjectMetadataList1);
      assertFalse(boolean0);
      assertFalse(catalogObjectMetadataList1.equals((Object)catalogObjectMetadataList0));
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ArrayList<CatalogObjectMetadata> arrayList0 = new ArrayList<CatalogObjectMetadata>();
      CatalogObjectMetadataList catalogObjectMetadataList0 = new CatalogObjectMetadataList(arrayList0);
      CatalogObjectMetadataList catalogObjectMetadataList1 = new CatalogObjectMetadataList(arrayList0);
      boolean boolean0 = catalogObjectMetadataList1.equals(catalogObjectMetadataList0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ArrayList<CatalogObjectMetadata> arrayList0 = new ArrayList<CatalogObjectMetadata>();
      CatalogObjectMetadataList catalogObjectMetadataList0 = new CatalogObjectMetadataList(arrayList0);
      List<CatalogObjectMetadata> list0 = catalogObjectMetadataList0.getObjectMetadataList();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CatalogObjectMetadataList catalogObjectMetadataList0 = new CatalogObjectMetadataList((List<CatalogObjectMetadata>) null);
      boolean boolean0 = catalogObjectMetadataList0.canEqual((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Vector<CatalogObjectMetadata> vector0 = new Vector<CatalogObjectMetadata>();
      CatalogObjectMetadataList catalogObjectMetadataList0 = new CatalogObjectMetadataList(vector0);
      boolean boolean0 = catalogObjectMetadataList0.canEqual(catalogObjectMetadataList0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ArrayList<CatalogObjectMetadata> arrayList0 = new ArrayList<CatalogObjectMetadata>();
      CatalogObjectMetadataList catalogObjectMetadataList0 = new CatalogObjectMetadataList(arrayList0);
      Stack<Metadata> stack0 = new Stack<Metadata>();
      CatalogObjectMetadata catalogObjectMetadata0 = new CatalogObjectMetadata(")", "70KnCW3", "%q.JzriE6:MkH-UN", "Ny-zD=.FF0mSHMU", 1645L, "%25\"i{3+", "", stack0, "%q.JzriE6:MkH-UN");
      arrayList0.add(catalogObjectMetadata0);
      List<CatalogObjectMetadata> list0 = catalogObjectMetadataList0.getObjectMetadataList();
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CatalogObjectMetadataList catalogObjectMetadataList0 = new CatalogObjectMetadataList((List<CatalogObjectMetadata>) null);
      List<CatalogObjectMetadata> list0 = catalogObjectMetadataList0.getObjectMetadataList();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ArrayList<CatalogObjectMetadata> arrayList0 = new ArrayList<CatalogObjectMetadata>();
      CatalogObjectMetadataList catalogObjectMetadataList0 = new CatalogObjectMetadataList(arrayList0);
      boolean boolean0 = catalogObjectMetadataList0.equals(catalogObjectMetadataList0);
      assertTrue(boolean0);
  }
}
