/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 12:54:10 GMT 2019
 */

package org.ow2.proactive.catalog.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.dto.DependsOnCatalogObject;

public class DependsOnCatalogObject_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject("m-Bo'Xj iu\"qGe/a,", "m-Bo'Xj iu\"qGe/a,", true);
      DependsOnCatalogObject dependsOnCatalogObject1 = new DependsOnCatalogObject("m-Bo'Xj iu\"qGe/a,", "U{t", true);
      boolean boolean0 = dependsOnCatalogObject0.equals(dependsOnCatalogObject1);
      assertFalse(dependsOnCatalogObject1.equals((Object)dependsOnCatalogObject0));
      assertTrue(dependsOnCatalogObject1.isInCatalog());
      assertFalse(boolean0);
      assertEquals("m-Bo'Xj iu\"qGe/a,", dependsOnCatalogObject1.getBucketAndObjectName());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject((String) null, (String) null, true);
      String string0 = dependsOnCatalogObject0.toString();
      assertEquals("DependsOnCatalogObject(bucketAndObjectName=null, revisionCommitTime=null, isInCatalog=true)", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject(".w", ".w", false);
      dependsOnCatalogObject0.hashCode();
      assertFalse(dependsOnCatalogObject0.isInCatalog());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject((String) null, (String) null, true);
      dependsOnCatalogObject0.hashCode();
      assertTrue(dependsOnCatalogObject0.isInCatalog());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject((String) null, (String) null, true);
      boolean boolean0 = dependsOnCatalogObject0.equals(dependsOnCatalogObject0);
      assertTrue(boolean0);
      assertTrue(dependsOnCatalogObject0.isInCatalog());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject("$VALUES", "2E81", false);
      Object object0 = new Object();
      boolean boolean0 = dependsOnCatalogObject0.equals(object0);
      assertEquals("2E81", dependsOnCatalogObject0.getRevisionCommitTime());
      assertEquals("$VALUES", dependsOnCatalogObject0.getBucketAndObjectName());
      assertFalse(boolean0);
      assertFalse(dependsOnCatalogObject0.isInCatalog());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject((String) null, (String) null, true);
      DependsOnCatalogObject dependsOnCatalogObject1 = new DependsOnCatalogObject((String) null, (String) null, true);
      boolean boolean0 = dependsOnCatalogObject1.equals(dependsOnCatalogObject0);
      assertTrue(boolean0);
      assertTrue(dependsOnCatalogObject1.isInCatalog());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject((String) null, (String) null, false);
      DependsOnCatalogObject dependsOnCatalogObject1 = new DependsOnCatalogObject("6gP(<'NRy+r", (String) null, false);
      boolean boolean0 = dependsOnCatalogObject0.equals(dependsOnCatalogObject1);
      assertFalse(dependsOnCatalogObject1.equals((Object)dependsOnCatalogObject0));
      assertFalse(dependsOnCatalogObject1.isInCatalog());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject("<-Bo'Xj iu\"qGe/a,", "<-Bo'Xj iu\"qGe/a,", false);
      DependsOnCatalogObject dependsOnCatalogObject1 = new DependsOnCatalogObject("", "<-Bo'Xj iu\"qGe/a,", false);
      boolean boolean0 = dependsOnCatalogObject0.equals(dependsOnCatalogObject1);
      assertEquals("<-Bo'Xj iu\"qGe/a,", dependsOnCatalogObject1.getRevisionCommitTime());
      assertFalse(boolean0);
      assertFalse(dependsOnCatalogObject1.isInCatalog());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject((String) null, (String) null, false);
      DependsOnCatalogObject dependsOnCatalogObject1 = new DependsOnCatalogObject((String) null, "Eub&9f4yfHAu.UpD5bEm", false);
      boolean boolean0 = dependsOnCatalogObject0.equals(dependsOnCatalogObject1);
      assertFalse(dependsOnCatalogObject1.equals((Object)dependsOnCatalogObject0));
      assertFalse(boolean0);
      assertFalse(dependsOnCatalogObject1.isInCatalog());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject("<-Bo'Xj iu\"qGe/a,", "<-Bo'Xj iu\"qGe/a,", false);
      DependsOnCatalogObject dependsOnCatalogObject1 = new DependsOnCatalogObject("<-Bo'Xj iu\"qGe/a,", "<-Bo'Xj iu\"qGe/a,", false);
      boolean boolean0 = dependsOnCatalogObject1.equals(dependsOnCatalogObject0);
      assertTrue(boolean0);
      assertFalse(dependsOnCatalogObject1.isInCatalog());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject("", "SjBz#Y^", false);
      DependsOnCatalogObject dependsOnCatalogObject1 = new DependsOnCatalogObject("", "SjBz#Y^", true);
      boolean boolean0 = dependsOnCatalogObject0.equals(dependsOnCatalogObject1);
      assertEquals("", dependsOnCatalogObject1.getBucketAndObjectName());
      assertFalse(boolean0);
      assertTrue(dependsOnCatalogObject1.isInCatalog());
      assertEquals("SjBz#Y^", dependsOnCatalogObject1.getRevisionCommitTime());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject("$VALUES", "2E81", false);
      String string0 = dependsOnCatalogObject0.getRevisionCommitTime();
      assertFalse(dependsOnCatalogObject0.isInCatalog());
      assertEquals("$VALUES", dependsOnCatalogObject0.getBucketAndObjectName());
      assertEquals("2E81", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject("$VALUES", "2E81", false);
      boolean boolean0 = dependsOnCatalogObject0.isInCatalog();
      assertEquals("$VALUES", dependsOnCatalogObject0.getBucketAndObjectName());
      assertFalse(boolean0);
      assertEquals("2E81", dependsOnCatalogObject0.getRevisionCommitTime());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject("$VALUES", "2E81", false);
      String string0 = dependsOnCatalogObject0.getBucketAndObjectName();
      assertFalse(dependsOnCatalogObject0.isInCatalog());
      assertEquals("$VALUES", string0);
      assertEquals("2E81", dependsOnCatalogObject0.getRevisionCommitTime());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject("$VALUES", "2E81", false);
      dependsOnCatalogObject0.canEqual("2E81");
      assertEquals("$VALUES", dependsOnCatalogObject0.getBucketAndObjectName());
      assertEquals("2E81", dependsOnCatalogObject0.getRevisionCommitTime());
      assertFalse(dependsOnCatalogObject0.isInCatalog());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject("f$$ {b`#/C 9IQ", "f$$ {b`#/C 9IQ", false);
      dependsOnCatalogObject0.canEqual(dependsOnCatalogObject0);
      assertFalse(dependsOnCatalogObject0.isInCatalog());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject("", "", false);
      dependsOnCatalogObject0.getBucketAndObjectName();
      assertFalse(dependsOnCatalogObject0.isInCatalog());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject((String) null, "DependsOnCatalogObject(bucketAndObjectName=WC{WPSPoKICg|{, revisionCommitTime=DependsOnCatalogObject(bucketAndObjectName=, isInCatalog=true)", true);
      String string0 = dependsOnCatalogObject0.getBucketAndObjectName();
      assertTrue(dependsOnCatalogObject0.isInCatalog());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject(", isInCatalog=", "", false);
      String string0 = dependsOnCatalogObject0.getRevisionCommitTime();
      assertFalse(dependsOnCatalogObject0.isInCatalog());
      assertEquals("", string0);
      assertEquals(", isInCatalog=", dependsOnCatalogObject0.getBucketAndObjectName());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject("WRITE_ONLY", (String) null, true);
      String string0 = dependsOnCatalogObject0.getRevisionCommitTime();
      assertNull(string0);
      assertTrue(dependsOnCatalogObject0.isInCatalog());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject("6xe? <-0h}4D`", "0\u0006bUd7NO<no!", true);
      boolean boolean0 = dependsOnCatalogObject0.isInCatalog();
      assertEquals("0\u0006bUd7NO<no!", dependsOnCatalogObject0.getRevisionCommitTime());
      assertTrue(boolean0);
      assertEquals("6xe? <-0h}4D`", dependsOnCatalogObject0.getBucketAndObjectName());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      DependsOnCatalogObject dependsOnCatalogObject0 = new DependsOnCatalogObject("6xe? <-0h}4D`", "0\u0006bUd7NO<no!", true);
      dependsOnCatalogObject0.hashCode();
      assertTrue(dependsOnCatalogObject0.isInCatalog());
      assertEquals("6xe? <-0h}4D`", dependsOnCatalogObject0.getBucketAndObjectName());
      assertEquals("0\u0006bUd7NO<no!", dependsOnCatalogObject0.getRevisionCommitTime());
  }
}
