/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 12:49:20 GMT 2019
 */

package org.ow2.proactive.catalog.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.dto.Metadata;
import org.ow2.proactive.catalog.repository.entity.KeyValueLabelMetadataEntity;

public class Metadata_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      KeyValueLabelMetadataEntity keyValueLabelMetadataEntity0 = new KeyValueLabelMetadataEntity();
      Metadata metadata0 = new Metadata(keyValueLabelMetadataEntity0);
      metadata0.setLabel("+F=");
      String string0 = metadata0.getLabel();
      assertEquals("+F=", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Metadata metadata0 = new Metadata();
      String string0 = metadata0.toString();
      assertEquals("Metadata(key=null, value=null, label=null)", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Metadata metadata0 = new Metadata("@bN,?1i*izh<", "@bN,?1i*izh<", "4EN9 4kg");
      String string0 = metadata0.getKey();
      assertEquals("4EN9 4kg", metadata0.getLabel());
      assertEquals("@bN,?1i*izh<", metadata0.getValue());
      assertEquals("@bN,?1i*izh<", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Metadata metadata0 = new Metadata();
      metadata0.hashCode();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Metadata metadata0 = new Metadata();
      metadata0.setLabel("Metadata(key=null, value=null, label=null)");
      assertEquals("Metadata(key=null, value=null, label=null)", metadata0.getLabel());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Metadata metadata0 = new Metadata();
      Object object0 = new Object();
      boolean boolean0 = metadata0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Metadata metadata0 = new Metadata();
      boolean boolean0 = metadata0.equals(metadata0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Metadata metadata0 = new Metadata();
      KeyValueLabelMetadataEntity keyValueLabelMetadataEntity0 = new KeyValueLabelMetadataEntity();
      Metadata metadata1 = new Metadata(keyValueLabelMetadataEntity0);
      boolean boolean0 = metadata0.equals(metadata1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Metadata metadata0 = new Metadata();
      Metadata metadata1 = new Metadata("T~CP)l,M8CpOJ;o", "T~CP)l,M8CpOJ;o", "T~CP)l,M8CpOJ;o");
      boolean boolean0 = metadata0.equals(metadata1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Metadata metadata0 = new Metadata();
      String string0 = metadata0.getKey();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Metadata metadata0 = new Metadata();
      String string0 = metadata0.getLabel();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Metadata metadata0 = new Metadata();
      String string0 = metadata0.getValue();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Metadata metadata0 = null;
      try {
        metadata0 = new Metadata((KeyValueLabelMetadataEntity) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Metadata metadata0 = new Metadata();
      metadata0.setKey("");
      String string0 = metadata0.getKey();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Metadata metadata0 = new Metadata("", "com.google.common.base.Predicates$ObjectPredicate", "");
      String string0 = metadata0.getLabel();
      assertEquals("", metadata0.getKey());
      assertEquals("com.google.common.base.Predicates$ObjectPredicate", metadata0.getValue());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Metadata metadata0 = new Metadata("", "com.google.common.base.Predicates$ObjectPredicate", "");
      assertEquals("com.google.common.base.Predicates$ObjectPredicate", metadata0.getValue());
      
      metadata0.setValue("");
      metadata0.getValue();
      assertEquals("", metadata0.getKey());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Metadata metadata0 = new Metadata("@bN,?1i*izh<", "@bN,?1i*izh<", "4EN9 4kg");
      String string0 = metadata0.getValue();
      assertEquals("4EN9 4kg", metadata0.getLabel());
      assertEquals("@bN,?1i*izh<", string0);
      assertEquals("@bN,?1i*izh<", metadata0.getKey());
  }
}
