/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 14:45:42 GMT 2019
 */

package org.ow2.proactive.catalog.util;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Collection;
import java.util.LinkedList;
import java.util.List;
import java.util.TreeSet;
import org.ow2.proactive.catalog.dto.Metadata;
import org.ow2.proactive.catalog.repository.entity.KeyValueLabelMetadataEntity;
import org.ow2.proactive.catalog.util.KeyValueEntityToDtoTransformer;

public class KeyValueEntityToDtoTransformer_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        KeyValueEntityToDtoTransformer.to((Collection<? extends KeyValueLabelMetadataEntity>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      KeyValueEntityToDtoTransformer keyValueEntityToDtoTransformer0 = new KeyValueEntityToDtoTransformer();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<KeyValueLabelMetadataEntity> linkedList0 = new LinkedList<KeyValueLabelMetadataEntity>();
      KeyValueLabelMetadataEntity keyValueLabelMetadataEntity0 = new KeyValueLabelMetadataEntity();
      linkedList0.offerLast(keyValueLabelMetadataEntity0);
      List<Metadata> list0 = KeyValueEntityToDtoTransformer.to(linkedList0);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TreeSet<KeyValueLabelMetadataEntity> treeSet0 = new TreeSet<KeyValueLabelMetadataEntity>();
      List<Metadata> list0 = KeyValueEntityToDtoTransformer.to(treeSet0);
      assertEquals(0, list0.size());
  }
}
