/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:54:47 GMT 2019
 */

package org.ow2.proactive.catalog.util;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.util.KindAndContentTypeValidatorTest;

public class KindAndContentTypeValidatorTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      KindAndContentTypeValidatorTest kindAndContentTypeValidatorTest0 = new KindAndContentTypeValidatorTest();
  }
}
