/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:58:11 GMT 2019
 */

package org.ow2.proactive.catalog.util;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.util.PCWRuleParserTest;

public class PCWRuleParserTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PCWRuleParserTest pCWRuleParserTest0 = new PCWRuleParserTest();
  }
}
