/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:57:03 GMT 2019
 */

package org.ow2.proactive.catalog.util;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.util.PolicyParserTest;

public class PolicyParserTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PolicyParserTest policyParserTest0 = new PolicyParserTest();
  }
}
