/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 14:49:33 GMT 2019
 */

package org.ow2.proactive.catalog.util;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.util.ProActiveMySQL5InnoDBDialect;

public class ProActiveMySQL5InnoDBDialect_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ProActiveMySQL5InnoDBDialect proActiveMySQL5InnoDBDialect0 = new ProActiveMySQL5InnoDBDialect();
      String string0 = proActiveMySQL5InnoDBDialect0.getTableTypeString();
      assertEquals(" ENGINE=InnoDB DEFAULT CHARSET=utf8mb4", string0);
  }
}
