/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:51:24 GMT 2019
 */

package org.ow2.proactive.catalog.util;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.util.ProActiveCatalogObjectParserTest;

public class ProActiveCatalogObjectParserTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ProActiveCatalogObjectParserTest proActiveCatalogObjectParserTest0 = new ProActiveCatalogObjectParserTest();
  }
}
