/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:53:40 GMT 2019
 */

package org.ow2.proactive.catalog.util;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.util.RevisionCommitMessageBuilderTest;

public class RevisionCommitMessageBuilderTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RevisionCommitMessageBuilderTest revisionCommitMessageBuilderTest0 = new RevisionCommitMessageBuilderTest();
  }
}
