/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:52:32 GMT 2019
 */

package org.ow2.proactive.catalog.util;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.util.ScriptParserTest;

public class ScriptParserTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ScriptParserTest scriptParserTest0 = new ScriptParserTest();
  }
}
