/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:49:07 GMT 2019
 */

package org.ow2.proactive.catalog.util;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.util.SeparatorUtilityTest;

public class SeparatorUtilityTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SeparatorUtilityTest separatorUtilityTest0 = new SeparatorUtilityTest();
  }
}
