var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":38,"id":4680,"methods":[{"el":20,"sc":2,"sl":16},{"el":23,"sc":2,"sl":21},{"el":27,"sc":5,"sl":25},{"el":30,"sc":5,"sl":28},{"el":34,"sc":5,"sl":32},{"el":37,"sc":5,"sl":35}],"name":"AwaitingConfirmation","sl":10}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_182":{"methods":[{"sl":16}],"name":"testCatchExceptionAndRollback","pass":true,"statements":[{"sl":19}]},"test_252":{"methods":[{"sl":16}],"name":"testStar","pass":true,"statements":[{"sl":19}]},"test_292":{"methods":[{"sl":16}],"name":"testFindUserByUsername","pass":true,"statements":[{"sl":19}]},"test_315":{"methods":[{"sl":16}],"name":"testDeleteUserAccount","pass":true,"statements":[{"sl":19}]},"test_35":{"methods":[{"sl":16}],"name":"testTransactionIsActive","pass":true,"statements":[{"sl":19}]},"test_386":{"methods":[{"sl":16}],"name":"testGetSessionFactory","pass":true,"statements":[{"sl":19}]},"test_408":{"methods":[{"sl":16}],"name":"testCreateUserAccountEmptyProfile","pass":true,"statements":[{"sl":19}]},"test_538":{"methods":[{"sl":16}],"name":"testSingleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":19}]},"test_58":{"methods":[{"sl":16}],"name":"testDeleteUserAccountThatDoesNot","pass":true,"statements":[{"sl":19}]},"test_602":{"methods":[{"sl":16}],"name":"testMultipleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":19}]},"test_693":{"methods":[{"sl":16}],"name":"testCatchRuntimeExceptionAndRollback","pass":true,"statements":[{"sl":19}]},"test_732":{"methods":[{"sl":16}],"name":"testTransactionTwiceSameThread","pass":true,"statements":[{"sl":19}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [35, 58, 386, 252, 602, 182, 732, 292, 538, 693, 408, 315], [], [], [35, 58, 386, 252, 602, 182, 732, 292, 538, 693, 408, 315], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
