var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":120,"id":5065,"methods":[{"el":40,"sc":5,"sl":37},{"el":47,"sc":5,"sl":42},{"el":52,"sc":5,"sl":49},{"el":57,"sc":5,"sl":54},{"el":63,"sc":2,"sl":59},{"el":68,"sc":2,"sl":65},{"el":73,"sc":2,"sl":70},{"el":78,"sc":2,"sl":75},{"el":83,"sc":2,"sl":80},{"el":88,"sc":2,"sl":85},{"el":93,"sc":2,"sl":90},{"el":98,"sc":2,"sl":95},{"el":103,"sc":2,"sl":100},{"el":108,"sc":2,"sl":105},{"el":113,"sc":2,"sl":110},{"el":118,"sc":2,"sl":115}],"name":"ContactListImpl","sl":14}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_182":{"methods":[{"sl":42}],"name":"testCatchExceptionAndRollback","pass":true,"statements":[{"sl":46}]},"test_252":{"methods":[{"sl":42}],"name":"testStar","pass":true,"statements":[{"sl":46}]},"test_292":{"methods":[{"sl":42}],"name":"testFindUserByUsername","pass":true,"statements":[{"sl":46}]},"test_315":{"methods":[{"sl":42}],"name":"testDeleteUserAccount","pass":true,"statements":[{"sl":46}]},"test_35":{"methods":[{"sl":42}],"name":"testTransactionIsActive","pass":true,"statements":[{"sl":46}]},"test_386":{"methods":[{"sl":42}],"name":"testGetSessionFactory","pass":true,"statements":[{"sl":46}]},"test_408":{"methods":[{"sl":42}],"name":"testCreateUserAccountEmptyProfile","pass":true,"statements":[{"sl":46}]},"test_538":{"methods":[{"sl":42}],"name":"testSingleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":46}]},"test_58":{"methods":[{"sl":42}],"name":"testDeleteUserAccountThatDoesNot","pass":true,"statements":[{"sl":46}]},"test_602":{"methods":[{"sl":42}],"name":"testMultipleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":46}]},"test_693":{"methods":[{"sl":42}],"name":"testCatchRuntimeExceptionAndRollback","pass":true,"statements":[{"sl":46}]},"test_732":{"methods":[{"sl":42}],"name":"testTransactionTwiceSameThread","pass":true,"statements":[{"sl":46}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [35, 58, 386, 252, 602, 182, 732, 292, 538, 693, 408, 315], [], [], [], [35, 58, 386, 252, 602, 182, 732, 292, 538, 693, 408, 315], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
