var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":156,"id":7364,"methods":[{"el":36,"sc":5,"sl":32},{"el":40,"sc":5,"sl":38},{"el":45,"sc":5,"sl":42},{"el":50,"sc":5,"sl":47},{"el":56,"sc":5,"sl":52},{"el":61,"sc":5,"sl":58},{"el":66,"sc":5,"sl":63},{"el":71,"sc":5,"sl":68},{"el":77,"sc":5,"sl":73},{"el":82,"sc":5,"sl":79},{"el":88,"sc":5,"sl":84},{"el":93,"sc":5,"sl":90},{"el":98,"sc":5,"sl":95},{"el":103,"sc":5,"sl":100},{"el":108,"sc":5,"sl":105},{"el":113,"sc":5,"sl":110},{"el":119,"sc":5,"sl":115},{"el":131,"sc":5,"sl":121},{"el":136,"sc":5,"sl":133},{"el":144,"sc":5,"sl":138},{"el":150,"sc":5,"sl":146},{"el":154,"sc":5,"sl":151}],"name":"LabelImpl","sl":16}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_182":{"methods":[{"sl":32}],"name":"testCatchExceptionAndRollback","pass":true,"statements":[{"sl":35}]},"test_252":{"methods":[{"sl":32}],"name":"testStar","pass":true,"statements":[{"sl":35}]},"test_292":{"methods":[{"sl":32}],"name":"testFindUserByUsername","pass":true,"statements":[{"sl":35}]},"test_315":{"methods":[{"sl":32}],"name":"testDeleteUserAccount","pass":true,"statements":[{"sl":35}]},"test_35":{"methods":[{"sl":32}],"name":"testTransactionIsActive","pass":true,"statements":[{"sl":35}]},"test_386":{"methods":[{"sl":32}],"name":"testGetSessionFactory","pass":true,"statements":[{"sl":35}]},"test_408":{"methods":[{"sl":32}],"name":"testCreateUserAccountEmptyProfile","pass":true,"statements":[{"sl":35}]},"test_538":{"methods":[{"sl":32}],"name":"testSingleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":35}]},"test_58":{"methods":[{"sl":32}],"name":"testDeleteUserAccountThatDoesNot","pass":true,"statements":[{"sl":35}]},"test_602":{"methods":[{"sl":32}],"name":"testMultipleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":35}]},"test_693":{"methods":[{"sl":32}],"name":"testCatchRuntimeExceptionAndRollback","pass":true,"statements":[{"sl":35}]},"test_732":{"methods":[{"sl":32}],"name":"testTransactionTwiceSameThread","pass":true,"statements":[{"sl":35}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [35, 252, 732, 292, 693, 408, 58, 386, 602, 182, 538, 315], [], [], [35, 252, 732, 292, 693, 408, 58, 386, 602, 182, 538, 315], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
