var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":117,"id":9138,"methods":[{"el":29,"sc":2,"sl":25},{"el":32,"sc":2,"sl":30},{"el":36,"sc":5,"sl":34},{"el":40,"sc":5,"sl":38},{"el":44,"sc":2,"sl":42},{"el":47,"sc":2,"sl":45},{"el":51,"sc":2,"sl":49},{"el":54,"sc":2,"sl":52},{"el":58,"sc":2,"sl":56},{"el":61,"sc":2,"sl":59},{"el":65,"sc":2,"sl":63},{"el":68,"sc":2,"sl":66},{"el":73,"sc":2,"sl":70},{"el":76,"sc":2,"sl":74},{"el":81,"sc":2,"sl":78},{"el":84,"sc":2,"sl":82},{"el":90,"sc":2,"sl":86},{"el":94,"sc":5,"sl":92},{"el":100,"sc":5,"sl":97},{"el":105,"sc":5,"sl":102},{"el":111,"sc":5,"sl":108},{"el":115,"sc":5,"sl":113}],"name":"SavedSearch","sl":10}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_182":{"methods":[{"sl":25}],"name":"testCatchExceptionAndRollback","pass":true,"statements":[{"sl":28}]},"test_252":{"methods":[{"sl":25}],"name":"testStar","pass":true,"statements":[{"sl":28}]},"test_292":{"methods":[{"sl":25}],"name":"testFindUserByUsername","pass":true,"statements":[{"sl":28}]},"test_315":{"methods":[{"sl":25}],"name":"testDeleteUserAccount","pass":true,"statements":[{"sl":28}]},"test_35":{"methods":[{"sl":25}],"name":"testTransactionIsActive","pass":true,"statements":[{"sl":28}]},"test_386":{"methods":[{"sl":25}],"name":"testGetSessionFactory","pass":true,"statements":[{"sl":28}]},"test_408":{"methods":[{"sl":25}],"name":"testCreateUserAccountEmptyProfile","pass":true,"statements":[{"sl":28}]},"test_538":{"methods":[{"sl":25}],"name":"testSingleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":28}]},"test_58":{"methods":[{"sl":25}],"name":"testDeleteUserAccountThatDoesNot","pass":true,"statements":[{"sl":28}]},"test_602":{"methods":[{"sl":25}],"name":"testMultipleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":28}]},"test_693":{"methods":[{"sl":25}],"name":"testCatchRuntimeExceptionAndRollback","pass":true,"statements":[{"sl":28}]},"test_732":{"methods":[{"sl":25}],"name":"testTransactionTwiceSameThread","pass":true,"statements":[{"sl":28}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [35, 252, 732, 292, 693, 408, 58, 386, 602, 182, 538, 315], [], [], [35, 252, 732, 292, 693, 408, 58, 386, 602, 182, 538, 315], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
