var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":111,"id":10260,"methods":[{"el":35,"sc":5,"sl":31},{"el":38,"sc":5,"sl":36},{"el":43,"sc":5,"sl":40},{"el":48,"sc":5,"sl":45},{"el":53,"sc":5,"sl":50},{"el":56,"sc":5,"sl":54},{"el":61,"sc":5,"sl":58},{"el":65,"sc":5,"sl":63},{"el":71,"sc":5,"sl":67},{"el":75,"sc":5,"sl":73},{"el":81,"sc":5,"sl":77},{"el":84,"sc":5,"sl":82},{"el":90,"sc":5,"sl":86},{"el":93,"sc":5,"sl":91},{"el":107,"sc":5,"sl":95},{"el":110,"sc":5,"sl":108}],"name":"UserGroupImpl","sl":18}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_182":{"methods":[{"sl":31}],"name":"testCatchExceptionAndRollback","pass":true,"statements":[{"sl":34}]},"test_252":{"methods":[{"sl":31}],"name":"testStar","pass":true,"statements":[{"sl":34}]},"test_292":{"methods":[{"sl":31}],"name":"testFindUserByUsername","pass":true,"statements":[{"sl":34}]},"test_315":{"methods":[{"sl":31}],"name":"testDeleteUserAccount","pass":true,"statements":[{"sl":34}]},"test_35":{"methods":[{"sl":31}],"name":"testTransactionIsActive","pass":true,"statements":[{"sl":34}]},"test_386":{"methods":[{"sl":31}],"name":"testGetSessionFactory","pass":true,"statements":[{"sl":34}]},"test_408":{"methods":[{"sl":31}],"name":"testCreateUserAccountEmptyProfile","pass":true,"statements":[{"sl":34}]},"test_538":{"methods":[{"sl":31}],"name":"testSingleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":34}]},"test_58":{"methods":[{"sl":31}],"name":"testDeleteUserAccountThatDoesNot","pass":true,"statements":[{"sl":34}]},"test_602":{"methods":[{"sl":31}],"name":"testMultipleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":34}]},"test_693":{"methods":[{"sl":31}],"name":"testCatchRuntimeExceptionAndRollback","pass":true,"statements":[{"sl":34}]},"test_732":{"methods":[{"sl":31}],"name":"testTransactionTwiceSameThread","pass":true,"statements":[{"sl":34}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [35, 58, 386, 252, 602, 182, 732, 292, 538, 693, 408, 315], [], [], [35, 58, 386, 252, 602, 182, 732, 292, 538, 693, 408, 315], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
