var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":179,"id":4692,"methods":[{"el":35,"sc":5,"sl":33},{"el":40,"sc":2,"sl":37},{"el":44,"sc":5,"sl":42},{"el":49,"sc":5,"sl":46},{"el":52,"sc":5,"sl":50},{"el":58,"sc":5,"sl":54},{"el":62,"sc":5,"sl":60},{"el":68,"sc":5,"sl":64},{"el":73,"sc":5,"sl":70},{"el":77,"sc":5,"sl":75},{"el":82,"sc":5,"sl":79},{"el":86,"sc":5,"sl":84},{"el":92,"sc":5,"sl":88},{"el":96,"sc":5,"sl":94},{"el":102,"sc":5,"sl":98},{"el":106,"sc":5,"sl":104},{"el":111,"sc":5,"sl":108},{"el":115,"sc":2,"sl":113},{"el":120,"sc":5,"sl":117},{"el":126,"sc":2,"sl":122},{"el":131,"sc":2,"sl":128},{"el":135,"sc":5,"sl":133},{"el":140,"sc":5,"sl":137},{"el":144,"sc":5,"sl":142},{"el":150,"sc":5,"sl":146},{"el":154,"sc":5,"sl":152},{"el":168,"sc":5,"sl":157},{"el":177,"sc":5,"sl":170}],"name":"BeaconImpl","sl":13}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_144":{"methods":[{"sl":33}],"name":"testStar","pass":true,"statements":[{"sl":34}]},"test_2":{"methods":[{"sl":33}],"name":"testGetSessionFactory","pass":true,"statements":[{"sl":34}]},"test_286":{"methods":[{"sl":33}],"name":"testDeleteUserAccount","pass":true,"statements":[{"sl":34}]},"test_290":{"methods":[{"sl":33}],"name":"testSingleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":34}]},"test_301":{"methods":[{"sl":33}],"name":"testDeleteUserAccountThatDoesNot","pass":true,"statements":[{"sl":34}]},"test_335":{"methods":[{"sl":33}],"name":"testMultipleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":34}]},"test_360":{"methods":[{"sl":33}],"name":"testFindUserByUsername","pass":true,"statements":[{"sl":34}]},"test_550":{"methods":[{"sl":33}],"name":"testTransactionIsActive","pass":true,"statements":[{"sl":34}]},"test_571":{"methods":[{"sl":33}],"name":"testTransactionTwiceSameThread","pass":true,"statements":[{"sl":34}]},"test_588":{"methods":[{"sl":33}],"name":"testCatchExceptionAndRollback","pass":true,"statements":[{"sl":34}]},"test_607":{"methods":[{"sl":33}],"name":"testCreateUserAccountEmptyProfile","pass":true,"statements":[{"sl":34}]},"test_9":{"methods":[{"sl":33}],"name":"testCatchRuntimeExceptionAndRollback","pass":true,"statements":[{"sl":34}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [286, 588, 2, 9, 290, 360, 335, 571, 301, 550, 607, 144], [286, 588, 2, 9, 290, 360, 335, 571, 301, 550, 607, 144], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
