var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":89,"id":4909,"methods":[{"el":30,"sc":5,"sl":26},{"el":34,"sc":5,"sl":32},{"el":40,"sc":5,"sl":37},{"el":45,"sc":5,"sl":42},{"el":50,"sc":5,"sl":47},{"el":55,"sc":5,"sl":52},{"el":60,"sc":5,"sl":57},{"el":65,"sc":5,"sl":62},{"el":70,"sc":5,"sl":67},{"el":75,"sc":5,"sl":72},{"el":80,"sc":5,"sl":77},{"el":85,"sc":5,"sl":82}],"name":"BroadcastImpl","sl":18}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_144":{"methods":[{"sl":26}],"name":"testStar","pass":true,"statements":[{"sl":29}]},"test_2":{"methods":[{"sl":26}],"name":"testGetSessionFactory","pass":true,"statements":[{"sl":29}]},"test_286":{"methods":[{"sl":26}],"name":"testDeleteUserAccount","pass":true,"statements":[{"sl":29}]},"test_290":{"methods":[{"sl":26}],"name":"testSingleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":29}]},"test_301":{"methods":[{"sl":26}],"name":"testDeleteUserAccountThatDoesNot","pass":true,"statements":[{"sl":29}]},"test_335":{"methods":[{"sl":26}],"name":"testMultipleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":29}]},"test_360":{"methods":[{"sl":26}],"name":"testFindUserByUsername","pass":true,"statements":[{"sl":29}]},"test_550":{"methods":[{"sl":26}],"name":"testTransactionIsActive","pass":true,"statements":[{"sl":29}]},"test_571":{"methods":[{"sl":26}],"name":"testTransactionTwiceSameThread","pass":true,"statements":[{"sl":29}]},"test_588":{"methods":[{"sl":26}],"name":"testCatchExceptionAndRollback","pass":true,"statements":[{"sl":29}]},"test_607":{"methods":[{"sl":26}],"name":"testCreateUserAccountEmptyProfile","pass":true,"statements":[{"sl":29}]},"test_9":{"methods":[{"sl":26}],"name":"testCatchRuntimeExceptionAndRollback","pass":true,"statements":[{"sl":29}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [286, 588, 2, 9, 290, 360, 335, 571, 301, 550, 607, 144], [], [], [286, 588, 2, 9, 290, 360, 335, 571, 301, 550, 607, 144], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
