var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":132,"id":5017,"methods":[{"el":33,"sc":5,"sl":28},{"el":38,"sc":5,"sl":35},{"el":42,"sc":5,"sl":40},{"el":46,"sc":5,"sl":44},{"el":51,"sc":5,"sl":48},{"el":55,"sc":5,"sl":53},{"el":62,"sc":5,"sl":58},{"el":66,"sc":5,"sl":64},{"el":71,"sc":5,"sl":68},{"el":75,"sc":5,"sl":73},{"el":80,"sc":5,"sl":77},{"el":84,"sc":5,"sl":82},{"el":90,"sc":5,"sl":86},{"el":94,"sc":5,"sl":92},{"el":99,"sc":5,"sl":96},{"el":103,"sc":5,"sl":101},{"el":109,"sc":5,"sl":105},{"el":114,"sc":5,"sl":111},{"el":118,"sc":5,"sl":116},{"el":122,"sc":5,"sl":120},{"el":127,"sc":5,"sl":124},{"el":131,"sc":5,"sl":129}],"name":"CommentImpl","sl":12}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_144":{"methods":[{"sl":28}],"name":"testStar","pass":true,"statements":[{"sl":32}]},"test_2":{"methods":[{"sl":28}],"name":"testGetSessionFactory","pass":true,"statements":[{"sl":32}]},"test_286":{"methods":[{"sl":28}],"name":"testDeleteUserAccount","pass":true,"statements":[{"sl":32}]},"test_290":{"methods":[{"sl":28}],"name":"testSingleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":32}]},"test_301":{"methods":[{"sl":28}],"name":"testDeleteUserAccountThatDoesNot","pass":true,"statements":[{"sl":32}]},"test_335":{"methods":[{"sl":28}],"name":"testMultipleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":32}]},"test_360":{"methods":[{"sl":28}],"name":"testFindUserByUsername","pass":true,"statements":[{"sl":32}]},"test_550":{"methods":[{"sl":28}],"name":"testTransactionIsActive","pass":true,"statements":[{"sl":32}]},"test_571":{"methods":[{"sl":28}],"name":"testTransactionTwiceSameThread","pass":true,"statements":[{"sl":32}]},"test_588":{"methods":[{"sl":28}],"name":"testCatchExceptionAndRollback","pass":true,"statements":[{"sl":32}]},"test_607":{"methods":[{"sl":28}],"name":"testCreateUserAccountEmptyProfile","pass":true,"statements":[{"sl":32}]},"test_9":{"methods":[{"sl":28}],"name":"testCatchRuntimeExceptionAndRollback","pass":true,"statements":[{"sl":32}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [286, 588, 2, 9, 290, 360, 335, 571, 301, 550, 607, 144], [], [], [], [286, 588, 2, 9, 290, 360, 335, 571, 301, 550, 607, 144], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
