var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":108,"id":9080,"methods":[{"el":31,"sc":2,"sl":27},{"el":34,"sc":2,"sl":32},{"el":38,"sc":2,"sl":36},{"el":41,"sc":2,"sl":39},{"el":46,"sc":2,"sl":43},{"el":49,"sc":2,"sl":47},{"el":53,"sc":2,"sl":51},{"el":56,"sc":2,"sl":54},{"el":60,"sc":2,"sl":58},{"el":63,"sc":2,"sl":61},{"el":67,"sc":2,"sl":65},{"el":70,"sc":2,"sl":68},{"el":74,"sc":2,"sl":72},{"el":77,"sc":2,"sl":75},{"el":81,"sc":2,"sl":79},{"el":84,"sc":2,"sl":82},{"el":88,"sc":2,"sl":86},{"el":91,"sc":2,"sl":89},{"el":95,"sc":2,"sl":93},{"el":98,"sc":2,"sl":96},{"el":102,"sc":2,"sl":100},{"el":105,"sc":2,"sl":103}],"name":"SavedHistoryFilter","sl":8}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_144":{"methods":[{"sl":27}],"name":"testStar","pass":true,"statements":[{"sl":30}]},"test_2":{"methods":[{"sl":27}],"name":"testGetSessionFactory","pass":true,"statements":[{"sl":30}]},"test_286":{"methods":[{"sl":27}],"name":"testDeleteUserAccount","pass":true,"statements":[{"sl":30}]},"test_290":{"methods":[{"sl":27}],"name":"testSingleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":30}]},"test_301":{"methods":[{"sl":27}],"name":"testDeleteUserAccountThatDoesNot","pass":true,"statements":[{"sl":30}]},"test_335":{"methods":[{"sl":27}],"name":"testMultipleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":30}]},"test_360":{"methods":[{"sl":27}],"name":"testFindUserByUsername","pass":true,"statements":[{"sl":30}]},"test_550":{"methods":[{"sl":27}],"name":"testTransactionIsActive","pass":true,"statements":[{"sl":30}]},"test_571":{"methods":[{"sl":27}],"name":"testTransactionTwiceSameThread","pass":true,"statements":[{"sl":30}]},"test_588":{"methods":[{"sl":27}],"name":"testCatchExceptionAndRollback","pass":true,"statements":[{"sl":30}]},"test_607":{"methods":[{"sl":27}],"name":"testCreateUserAccountEmptyProfile","pass":true,"statements":[{"sl":30}]},"test_9":{"methods":[{"sl":27}],"name":"testCatchRuntimeExceptionAndRollback","pass":true,"statements":[{"sl":30}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [286, 588, 2, 9, 290, 360, 335, 571, 301, 550, 607, 144], [], [], [286, 588, 2, 9, 290, 360, 335, 571, 301, 550, 607, 144], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
