var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":117,"id":9138,"methods":[{"el":29,"sc":2,"sl":25},{"el":32,"sc":2,"sl":30},{"el":36,"sc":5,"sl":34},{"el":40,"sc":5,"sl":38},{"el":44,"sc":2,"sl":42},{"el":47,"sc":2,"sl":45},{"el":51,"sc":2,"sl":49},{"el":54,"sc":2,"sl":52},{"el":58,"sc":2,"sl":56},{"el":61,"sc":2,"sl":59},{"el":65,"sc":2,"sl":63},{"el":68,"sc":2,"sl":66},{"el":73,"sc":2,"sl":70},{"el":76,"sc":2,"sl":74},{"el":81,"sc":2,"sl":78},{"el":84,"sc":2,"sl":82},{"el":90,"sc":2,"sl":86},{"el":94,"sc":5,"sl":92},{"el":100,"sc":5,"sl":97},{"el":105,"sc":5,"sl":102},{"el":111,"sc":5,"sl":108},{"el":115,"sc":5,"sl":113}],"name":"SavedSearch","sl":10}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_144":{"methods":[{"sl":25}],"name":"testStar","pass":true,"statements":[{"sl":28}]},"test_2":{"methods":[{"sl":25}],"name":"testGetSessionFactory","pass":true,"statements":[{"sl":28}]},"test_286":{"methods":[{"sl":25}],"name":"testDeleteUserAccount","pass":true,"statements":[{"sl":28}]},"test_290":{"methods":[{"sl":25}],"name":"testSingleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":28}]},"test_301":{"methods":[{"sl":25}],"name":"testDeleteUserAccountThatDoesNot","pass":true,"statements":[{"sl":28}]},"test_335":{"methods":[{"sl":25}],"name":"testMultipleTransactionsMultipleJunitsOfWork","pass":true,"statements":[{"sl":28}]},"test_360":{"methods":[{"sl":25}],"name":"testFindUserByUsername","pass":true,"statements":[{"sl":28}]},"test_550":{"methods":[{"sl":25}],"name":"testTransactionIsActive","pass":true,"statements":[{"sl":28}]},"test_571":{"methods":[{"sl":25}],"name":"testTransactionTwiceSameThread","pass":true,"statements":[{"sl":28}]},"test_588":{"methods":[{"sl":25}],"name":"testCatchExceptionAndRollback","pass":true,"statements":[{"sl":28}]},"test_607":{"methods":[{"sl":25}],"name":"testCreateUserAccountEmptyProfile","pass":true,"statements":[{"sl":28}]},"test_9":{"methods":[{"sl":25}],"name":"testCatchRuntimeExceptionAndRollback","pass":true,"statements":[{"sl":28}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [286, 9, 290, 360, 571, 607, 588, 2, 335, 301, 550, 144], [], [], [286, 9, 290, 360, 571, 607, 588, 2, 335, 301, 550, 144], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
