/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 13:16:59 GMT 2019
 */

package org.ow2.proactive.catalog.graphql.handler.catalogobject;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import java.util.Optional;
import org.hibernate.collection.internal.PersistentBag;
import org.hibernate.collection.internal.PersistentIdentifierBag;
import org.ow2.proactive.catalog.graphql.bean.argument.CatalogObjectBucketNameWhereArgs;
import org.ow2.proactive.catalog.graphql.bean.argument.CatalogObjectKindWhereArgs;
import org.ow2.proactive.catalog.graphql.bean.argument.CatalogObjectMetadataArgs;
import org.ow2.proactive.catalog.graphql.bean.argument.CatalogObjectNameWhereArgs;
import org.ow2.proactive.catalog.graphql.bean.argument.CatalogObjectWhereArgs;
import org.ow2.proactive.catalog.graphql.bean.argument.StringWhereArgs;
import org.ow2.proactive.catalog.graphql.handler.catalogobject.CatalogObjectMetadataFilterHandler;
import org.ow2.proactive.catalog.repository.entity.CatalogObjectRevisionEntity;
import org.springframework.data.jpa.domain.Specification;

public class CatalogObjectMetadataFilterHandler_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CatalogObjectMetadataFilterHandler catalogObjectMetadataFilterHandler0 = new CatalogObjectMetadataFilterHandler();
      CatalogObjectWhereArgs catalogObjectWhereArgs0 = new CatalogObjectWhereArgs();
      Optional<Specification<CatalogObjectRevisionEntity>> optional0 = catalogObjectMetadataFilterHandler0.handle(catalogObjectWhereArgs0);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CatalogObjectMetadataFilterHandler catalogObjectMetadataFilterHandler0 = new CatalogObjectMetadataFilterHandler();
      CatalogObjectWhereArgs catalogObjectWhereArgs0 = new CatalogObjectWhereArgs();
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs0 = new CatalogObjectNameWhereArgs("", "", "", "", "X*aveTVz4;pH", "", "", "");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("", catalogObjectNameWhereArgs0);
      catalogObjectWhereArgs0.setMetadataArg(catalogObjectMetadataArgs0);
      Optional<Specification<CatalogObjectRevisionEntity>> optional0 = catalogObjectMetadataFilterHandler0.handle(catalogObjectWhereArgs0);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CatalogObjectMetadataFilterHandler catalogObjectMetadataFilterHandler0 = new CatalogObjectMetadataFilterHandler();
      PersistentBag persistentBag0 = new PersistentBag();
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs0 = new CatalogObjectNameWhereArgs((String) null, "", "", (String) null, "", "Q0zC2@5X9Emw/}3n`@", "", "~mY");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("", catalogObjectNameWhereArgs0);
      CatalogObjectKindWhereArgs catalogObjectKindWhereArgs0 = new CatalogObjectKindWhereArgs();
      CatalogObjectWhereArgs catalogObjectWhereArgs0 = new CatalogObjectWhereArgs(persistentBag0, persistentBag0, catalogObjectMetadataArgs0, (CatalogObjectBucketNameWhereArgs) null, catalogObjectKindWhereArgs0, catalogObjectNameWhereArgs0);
      Optional<Specification<CatalogObjectRevisionEntity>> optional0 = catalogObjectMetadataFilterHandler0.handle(catalogObjectWhereArgs0);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CatalogObjectMetadataFilterHandler catalogObjectMetadataFilterHandler0 = new CatalogObjectMetadataFilterHandler();
      PersistentIdentifierBag persistentIdentifierBag0 = new PersistentIdentifierBag();
      CatalogObjectBucketNameWhereArgs catalogObjectBucketNameWhereArgs0 = new CatalogObjectBucketNameWhereArgs();
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("qz]@'dyQ;S", catalogObjectBucketNameWhereArgs0);
      CatalogObjectKindWhereArgs catalogObjectKindWhereArgs0 = new CatalogObjectKindWhereArgs();
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs0 = new CatalogObjectNameWhereArgs();
      CatalogObjectWhereArgs catalogObjectWhereArgs0 = new CatalogObjectWhereArgs(persistentIdentifierBag0, persistentIdentifierBag0, catalogObjectMetadataArgs0, catalogObjectBucketNameWhereArgs0, catalogObjectKindWhereArgs0, catalogObjectNameWhereArgs0);
      Optional<Specification<CatalogObjectRevisionEntity>> optional0 = catalogObjectMetadataFilterHandler0.handle(catalogObjectWhereArgs0);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CatalogObjectMetadataFilterHandler catalogObjectMetadataFilterHandler0 = new CatalogObjectMetadataFilterHandler();
      StringWhereArgs stringWhereArgs0 = new StringWhereArgs();
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("Y 5?", stringWhereArgs0);
      CatalogObjectBucketNameWhereArgs catalogObjectBucketNameWhereArgs0 = new CatalogObjectBucketNameWhereArgs();
      CatalogObjectKindWhereArgs catalogObjectKindWhereArgs0 = new CatalogObjectKindWhereArgs("Y 5?", "Y 5?", "Y 5?", "Y 5?", "Y 5?", "Y 5?", "", "");
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs0 = new CatalogObjectNameWhereArgs();
      CatalogObjectWhereArgs catalogObjectWhereArgs0 = new CatalogObjectWhereArgs((List<CatalogObjectWhereArgs>) null, (List<CatalogObjectWhereArgs>) null, catalogObjectMetadataArgs0, catalogObjectBucketNameWhereArgs0, catalogObjectKindWhereArgs0, catalogObjectNameWhereArgs0);
      stringWhereArgs0.setLike("Y 5?");
      Optional<Specification<CatalogObjectRevisionEntity>> optional0 = catalogObjectMetadataFilterHandler0.handle(catalogObjectWhereArgs0);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CatalogObjectMetadataFilterHandler catalogObjectMetadataFilterHandler0 = new CatalogObjectMetadataFilterHandler();
      // Undeclared exception!
      try { 
        catalogObjectMetadataFilterHandler0.handle((CatalogObjectWhereArgs) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
