/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 13:15:42 GMT 2019
 */

package org.ow2.proactive.catalog.graphql.handler.catalogobject;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import java.util.Optional;
import org.ow2.proactive.catalog.graphql.bean.argument.CatalogObjectBucketNameWhereArgs;
import org.ow2.proactive.catalog.graphql.bean.argument.CatalogObjectKindWhereArgs;
import org.ow2.proactive.catalog.graphql.bean.argument.CatalogObjectMetadataArgs;
import org.ow2.proactive.catalog.graphql.bean.argument.CatalogObjectNameWhereArgs;
import org.ow2.proactive.catalog.graphql.bean.argument.CatalogObjectWhereArgs;
import org.ow2.proactive.catalog.graphql.handler.catalogobject.CatalogObjectBucketNameFilterHandler;
import org.ow2.proactive.catalog.repository.entity.CatalogObjectRevisionEntity;
import org.springframework.data.jpa.domain.Specification;

public class CatalogObjectBucketNameFilterHandler_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CatalogObjectBucketNameFilterHandler catalogObjectBucketNameFilterHandler0 = new CatalogObjectBucketNameFilterHandler();
      CatalogObjectWhereArgs catalogObjectWhereArgs0 = new CatalogObjectWhereArgs();
      Optional<Specification<CatalogObjectRevisionEntity>> optional0 = catalogObjectBucketNameFilterHandler0.handle(catalogObjectWhereArgs0);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CatalogObjectBucketNameFilterHandler catalogObjectBucketNameFilterHandler0 = new CatalogObjectBucketNameFilterHandler();
      CatalogObjectWhereArgs catalogObjectWhereArgs0 = new CatalogObjectWhereArgs();
      CatalogObjectBucketNameWhereArgs catalogObjectBucketNameWhereArgs0 = new CatalogObjectBucketNameWhereArgs("", "", "jM", "org.ow2.proactive.catalog.graphql.handler.catalogobject.CatalogObjectBucketNameFilterHandler", "org.ow2.proactive.catalog.graphql.handler.catalogobject.CatalogObjectBucketNameFilterHandler", "org.ow2.proactive.catalog.graphql.handler.catalogobject.CatalogObjectBucketNameFilterHandler", "org.ow2.proactive.catalog.graphql.handler.catalogobject.CatalogObjectBucketNameFilterHandler", "");
      catalogObjectWhereArgs0.setBucketNameArg(catalogObjectBucketNameWhereArgs0);
      Optional<Specification<CatalogObjectRevisionEntity>> optional0 = catalogObjectBucketNameFilterHandler0.handle(catalogObjectWhereArgs0);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CatalogObjectBucketNameFilterHandler catalogObjectBucketNameFilterHandler0 = new CatalogObjectBucketNameFilterHandler();
      CatalogObjectWhereArgs catalogObjectWhereArgs0 = new CatalogObjectWhereArgs();
      CatalogObjectBucketNameWhereArgs catalogObjectBucketNameWhereArgs0 = new CatalogObjectBucketNameWhereArgs((String) null, "m8OaVj>\"+eIy&.\"O", "m8OaVj>\"+eIy&.\"O", "m8OaVj>\"+eIy&.\"O", "m8OaVj>\"+eIy&.\"O", "m8OaVj>\"+eIy&.\"O", (String) null, "");
      catalogObjectWhereArgs0.setBucketNameArg(catalogObjectBucketNameWhereArgs0);
      Optional<Specification<CatalogObjectRevisionEntity>> optional0 = catalogObjectBucketNameFilterHandler0.handle(catalogObjectWhereArgs0);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CatalogObjectBucketNameFilterHandler catalogObjectBucketNameFilterHandler0 = new CatalogObjectBucketNameFilterHandler();
      CatalogObjectWhereArgs catalogObjectWhereArgs0 = new CatalogObjectWhereArgs();
      CatalogObjectBucketNameWhereArgs catalogObjectBucketNameWhereArgs0 = new CatalogObjectBucketNameWhereArgs((String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, "");
      catalogObjectWhereArgs0.setBucketNameArg(catalogObjectBucketNameWhereArgs0);
      Optional<Specification<CatalogObjectRevisionEntity>> optional0 = catalogObjectBucketNameFilterHandler0.handle(catalogObjectWhereArgs0);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CatalogObjectBucketNameFilterHandler catalogObjectBucketNameFilterHandler0 = new CatalogObjectBucketNameFilterHandler();
      ArrayList<CatalogObjectWhereArgs> arrayList0 = new ArrayList<CatalogObjectWhereArgs>();
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs();
      CatalogObjectBucketNameWhereArgs catalogObjectBucketNameWhereArgs0 = new CatalogObjectBucketNameWhereArgs((String) null, (String) null, (String) null, ",15&tjF~6r,", "n}@Da8R1CZ", "n}@Da8R1CZ", ",15&tjF~6r,", "n}@Da8R1CZ");
      CatalogObjectWhereArgs catalogObjectWhereArgs0 = new CatalogObjectWhereArgs(arrayList0, arrayList0, catalogObjectMetadataArgs0, catalogObjectBucketNameWhereArgs0, (CatalogObjectKindWhereArgs) null, (CatalogObjectNameWhereArgs) null);
      Optional<Specification<CatalogObjectRevisionEntity>> optional0 = catalogObjectBucketNameFilterHandler0.handle(catalogObjectWhereArgs0);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CatalogObjectBucketNameFilterHandler catalogObjectBucketNameFilterHandler0 = new CatalogObjectBucketNameFilterHandler();
      CatalogObjectWhereArgs catalogObjectWhereArgs0 = new CatalogObjectWhereArgs();
      CatalogObjectBucketNameWhereArgs catalogObjectBucketNameWhereArgs0 = new CatalogObjectBucketNameWhereArgs();
      catalogObjectWhereArgs0.setBucketNameArg(catalogObjectBucketNameWhereArgs0);
      Optional<Specification<CatalogObjectRevisionEntity>> optional0 = catalogObjectBucketNameFilterHandler0.handle(catalogObjectWhereArgs0);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CatalogObjectBucketNameFilterHandler catalogObjectBucketNameFilterHandler0 = new CatalogObjectBucketNameFilterHandler();
      // Undeclared exception!
      try { 
        catalogObjectBucketNameFilterHandler0.handle((CatalogObjectWhereArgs) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
