/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 13:14:27 GMT 2019
 */

package org.ow2.proactive.catalog.graphql.handler.catalogobject;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import java.util.Optional;
import org.ow2.proactive.catalog.graphql.bean.argument.CatalogObjectBucketNameWhereArgs;
import org.ow2.proactive.catalog.graphql.bean.argument.CatalogObjectKindWhereArgs;
import org.ow2.proactive.catalog.graphql.bean.argument.CatalogObjectMetadataArgs;
import org.ow2.proactive.catalog.graphql.bean.argument.CatalogObjectNameWhereArgs;
import org.ow2.proactive.catalog.graphql.bean.argument.CatalogObjectWhereArgs;
import org.ow2.proactive.catalog.graphql.handler.catalogobject.CatalogObjectNameFilterHandler;
import org.ow2.proactive.catalog.repository.entity.CatalogObjectRevisionEntity;
import org.springframework.data.jpa.domain.Specification;

public class CatalogObjectNameFilterHandler_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CatalogObjectNameFilterHandler catalogObjectNameFilterHandler0 = new CatalogObjectNameFilterHandler();
      CatalogObjectWhereArgs catalogObjectWhereArgs0 = new CatalogObjectWhereArgs();
      Optional<Specification<CatalogObjectRevisionEntity>> optional0 = catalogObjectNameFilterHandler0.handle(catalogObjectWhereArgs0);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CatalogObjectNameFilterHandler catalogObjectNameFilterHandler0 = new CatalogObjectNameFilterHandler();
      LinkedList<CatalogObjectWhereArgs> linkedList0 = new LinkedList<CatalogObjectWhereArgs>();
      CatalogObjectKindWhereArgs catalogObjectKindWhereArgs0 = new CatalogObjectKindWhereArgs();
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("", catalogObjectKindWhereArgs0);
      CatalogObjectBucketNameWhereArgs catalogObjectBucketNameWhereArgs0 = new CatalogObjectBucketNameWhereArgs("", "", "", "", "", "org.ow2.proactive.catalog.graphql.handler.catalogobject.CatalogObjectNameFilterHandler", "/#", "QLZriw3cLa\"qCzX3");
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs0 = new CatalogObjectNameWhereArgs();
      CatalogObjectWhereArgs catalogObjectWhereArgs0 = new CatalogObjectWhereArgs(linkedList0, linkedList0, catalogObjectMetadataArgs0, catalogObjectBucketNameWhereArgs0, catalogObjectKindWhereArgs0, catalogObjectNameWhereArgs0);
      Optional<Specification<CatalogObjectRevisionEntity>> optional0 = catalogObjectNameFilterHandler0.handle(catalogObjectWhereArgs0);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CatalogObjectNameFilterHandler catalogObjectNameFilterHandler0 = new CatalogObjectNameFilterHandler();
      CatalogObjectWhereArgs catalogObjectWhereArgs0 = new CatalogObjectWhereArgs();
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs0 = new CatalogObjectNameWhereArgs("Path expected for join!", "Path expected for join!", "Path expected for join!", "Path expected for join!", "Path expected for join!", "Path expected for join!", "Path expected for join!", "Path expected for join!");
      catalogObjectWhereArgs0.setNameArg(catalogObjectNameWhereArgs0);
      Optional<Specification<CatalogObjectRevisionEntity>> optional0 = catalogObjectNameFilterHandler0.handle(catalogObjectWhereArgs0);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CatalogObjectNameFilterHandler catalogObjectNameFilterHandler0 = new CatalogObjectNameFilterHandler();
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs0 = new CatalogObjectNameWhereArgs((String) null, "W e|))0v;8kR", (String) null, (String) null, "Lg;[a@@yMB6T$@%", "W e|))0v;8kR", "W e|))0v;8kR", "");
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("Lg;[a@@yMB6T$@%", catalogObjectNameWhereArgs0);
      CatalogObjectBucketNameWhereArgs catalogObjectBucketNameWhereArgs0 = new CatalogObjectBucketNameWhereArgs();
      CatalogObjectKindWhereArgs catalogObjectKindWhereArgs0 = new CatalogObjectKindWhereArgs();
      CatalogObjectWhereArgs catalogObjectWhereArgs0 = new CatalogObjectWhereArgs((List<CatalogObjectWhereArgs>) null, (List<CatalogObjectWhereArgs>) null, catalogObjectMetadataArgs0, catalogObjectBucketNameWhereArgs0, catalogObjectKindWhereArgs0, catalogObjectNameWhereArgs0);
      Optional<Specification<CatalogObjectRevisionEntity>> optional0 = catalogObjectNameFilterHandler0.handle(catalogObjectWhereArgs0);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CatalogObjectNameFilterHandler catalogObjectNameFilterHandler0 = new CatalogObjectNameFilterHandler();
      CatalogObjectWhereArgs catalogObjectWhereArgs0 = new CatalogObjectWhereArgs();
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs0 = new CatalogObjectNameWhereArgs();
      catalogObjectNameWhereArgs0.setLike("");
      catalogObjectWhereArgs0.setNameArg(catalogObjectNameWhereArgs0);
      Optional<Specification<CatalogObjectRevisionEntity>> optional0 = catalogObjectNameFilterHandler0.handle(catalogObjectWhereArgs0);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CatalogObjectNameFilterHandler catalogObjectNameFilterHandler0 = new CatalogObjectNameFilterHandler();
      LinkedList<CatalogObjectWhereArgs> linkedList0 = new LinkedList<CatalogObjectWhereArgs>();
      CatalogObjectKindWhereArgs catalogObjectKindWhereArgs0 = new CatalogObjectKindWhereArgs();
      CatalogObjectMetadataArgs catalogObjectMetadataArgs0 = new CatalogObjectMetadataArgs("", catalogObjectKindWhereArgs0);
      CatalogObjectBucketNameWhereArgs catalogObjectBucketNameWhereArgs0 = new CatalogObjectBucketNameWhereArgs("", "", "", "", "", "org.ow2.proactive.catalog.graphql.handler.catalogobject.CatalogObjectNameFilterHandler", "/#", "QLZriw3cLa\"qCzX3");
      CatalogObjectNameWhereArgs catalogObjectNameWhereArgs0 = new CatalogObjectNameWhereArgs();
      catalogObjectNameWhereArgs0.setNotLike("5*2^pjRRD\"");
      CatalogObjectWhereArgs catalogObjectWhereArgs0 = new CatalogObjectWhereArgs(linkedList0, linkedList0, catalogObjectMetadataArgs0, catalogObjectBucketNameWhereArgs0, catalogObjectKindWhereArgs0, catalogObjectNameWhereArgs0);
      Optional<Specification<CatalogObjectRevisionEntity>> optional0 = catalogObjectNameFilterHandler0.handle(catalogObjectWhereArgs0);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CatalogObjectNameFilterHandler catalogObjectNameFilterHandler0 = new CatalogObjectNameFilterHandler();
      // Undeclared exception!
      try { 
        catalogObjectNameFilterHandler0.handle((CatalogObjectWhereArgs) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
