/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 12:58:46 GMT 2019
 */

package org.ow2.proactive.catalog.rest.query.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import graphql.parser.antlr.GraphqlParser;
import java.time.DayOfWeek;
import org.antlr.v4.runtime.InterpreterRuleContext;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.ow2.proactive.catalog.rest.query.parser.CatalogQueryLanguageBaseVisitor;
import org.ow2.proactive.catalog.rest.query.parser.CatalogQueryLanguageParser;

public class CatalogQueryLanguageBaseVisitor_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CatalogQueryLanguageBaseVisitor<GraphqlParser.VariableDefinitionContext> catalogQueryLanguageBaseVisitor0 = new CatalogQueryLanguageBaseVisitor<GraphqlParser.VariableDefinitionContext>();
      // Undeclared exception!
      try { 
        catalogQueryLanguageBaseVisitor0.visitOrExpression((CatalogQueryLanguageParser.OrExpressionContext) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CatalogQueryLanguageBaseVisitor<Integer> catalogQueryLanguageBaseVisitor0 = new CatalogQueryLanguageBaseVisitor<Integer>();
      // Undeclared exception!
      try { 
        catalogQueryLanguageBaseVisitor0.visitStart((CatalogQueryLanguageParser.StartContext) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CatalogQueryLanguageBaseVisitor<DayOfWeek> catalogQueryLanguageBaseVisitor0 = new CatalogQueryLanguageBaseVisitor<DayOfWeek>();
      // Undeclared exception!
      try { 
        catalogQueryLanguageBaseVisitor0.visitAtomicClause((CatalogQueryLanguageParser.AtomicClauseContext) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CatalogQueryLanguageBaseVisitor<Object> catalogQueryLanguageBaseVisitor0 = new CatalogQueryLanguageBaseVisitor<Object>();
      // Undeclared exception!
      try { 
        catalogQueryLanguageBaseVisitor0.visitClauseExpression((CatalogQueryLanguageParser.ClauseExpressionContext) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CatalogQueryLanguageBaseVisitor<GraphqlParser.VariableDefinitionContext> catalogQueryLanguageBaseVisitor0 = new CatalogQueryLanguageBaseVisitor<GraphqlParser.VariableDefinitionContext>();
      // Undeclared exception!
      try { 
        catalogQueryLanguageBaseVisitor0.visitAndExpression((CatalogQueryLanguageParser.AndExpressionContext) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CatalogQueryLanguageBaseVisitor<String> catalogQueryLanguageBaseVisitor0 = new CatalogQueryLanguageBaseVisitor<String>();
      // Undeclared exception!
      try { 
        catalogQueryLanguageBaseVisitor0.visitKeyValueClause((CatalogQueryLanguageParser.KeyValueClauseContext) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CatalogQueryLanguageBaseVisitor<Integer> catalogQueryLanguageBaseVisitor0 = new CatalogQueryLanguageBaseVisitor<Integer>();
      CatalogQueryLanguageParser.ExpressionContext catalogQueryLanguageParser_ExpressionContext0 = new CatalogQueryLanguageParser.ExpressionContext();
      CatalogQueryLanguageParser.ClauseExpressionContext catalogQueryLanguageParser_ClauseExpressionContext0 = new CatalogQueryLanguageParser.ClauseExpressionContext(catalogQueryLanguageParser_ExpressionContext0);
      CatalogQueryLanguageParser.AndExpressionContext catalogQueryLanguageParser_AndExpressionContext0 = new CatalogQueryLanguageParser.AndExpressionContext(catalogQueryLanguageParser_ClauseExpressionContext0);
      Integer integer0 = catalogQueryLanguageBaseVisitor0.visitAndExpression(catalogQueryLanguageParser_AndExpressionContext0);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CatalogQueryLanguageBaseVisitor<Object> catalogQueryLanguageBaseVisitor0 = new CatalogQueryLanguageBaseVisitor<Object>();
      CatalogQueryLanguageParser.ClauseContext catalogQueryLanguageParser_ClauseContext0 = new CatalogQueryLanguageParser.ClauseContext();
      CatalogQueryLanguageParser.AtomicClauseContext catalogQueryLanguageParser_AtomicClauseContext0 = new CatalogQueryLanguageParser.AtomicClauseContext(catalogQueryLanguageParser_ClauseContext0);
      Object object0 = catalogQueryLanguageBaseVisitor0.visitAtomicClause(catalogQueryLanguageParser_AtomicClauseContext0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CatalogQueryLanguageBaseVisitor<Integer> catalogQueryLanguageBaseVisitor0 = new CatalogQueryLanguageBaseVisitor<Integer>();
      CatalogQueryLanguageParser.ExpressionContext catalogQueryLanguageParser_ExpressionContext0 = new CatalogQueryLanguageParser.ExpressionContext();
      CatalogQueryLanguageParser.OrExpressionContext catalogQueryLanguageParser_OrExpressionContext0 = new CatalogQueryLanguageParser.OrExpressionContext(catalogQueryLanguageParser_ExpressionContext0);
      CatalogQueryLanguageParser.ClauseExpressionContext catalogQueryLanguageParser_ClauseExpressionContext0 = new CatalogQueryLanguageParser.ClauseExpressionContext(catalogQueryLanguageParser_OrExpressionContext0);
      Integer integer0 = catalogQueryLanguageBaseVisitor0.visitClauseExpression(catalogQueryLanguageParser_ClauseExpressionContext0);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CatalogQueryLanguageBaseVisitor<Object> catalogQueryLanguageBaseVisitor0 = new CatalogQueryLanguageBaseVisitor<Object>();
      CatalogQueryLanguageParser.ClauseContext catalogQueryLanguageParser_ClauseContext0 = new CatalogQueryLanguageParser.ClauseContext();
      CatalogQueryLanguageParser.KeyValueClauseContext catalogQueryLanguageParser_KeyValueClauseContext0 = new CatalogQueryLanguageParser.KeyValueClauseContext(catalogQueryLanguageParser_ClauseContext0);
      Object object0 = catalogQueryLanguageBaseVisitor0.visitKeyValueClause(catalogQueryLanguageParser_KeyValueClauseContext0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CatalogQueryLanguageBaseVisitor<Object> catalogQueryLanguageBaseVisitor0 = new CatalogQueryLanguageBaseVisitor<Object>();
      CatalogQueryLanguageParser.OrExpressionContext catalogQueryLanguageParser_OrExpressionContext0 = mock(CatalogQueryLanguageParser.OrExpressionContext.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(catalogQueryLanguageParser_OrExpressionContext0).getChildCount();
      Object object0 = catalogQueryLanguageBaseVisitor0.visitOrExpression(catalogQueryLanguageParser_OrExpressionContext0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CatalogQueryLanguageBaseVisitor<Object> catalogQueryLanguageBaseVisitor0 = new CatalogQueryLanguageBaseVisitor<Object>();
      InterpreterRuleContext interpreterRuleContext0 = new InterpreterRuleContext();
      GraphqlParser.NameContext graphqlParser_NameContext0 = new GraphqlParser.NameContext(interpreterRuleContext0, (-1));
      GraphqlParser.DefaultValueContext graphqlParser_DefaultValueContext0 = new GraphqlParser.DefaultValueContext(graphqlParser_NameContext0, (-1));
      GraphqlParser.ObjectValueContext graphqlParser_ObjectValueContext0 = new GraphqlParser.ObjectValueContext(graphqlParser_DefaultValueContext0, (-1));
      CatalogQueryLanguageParser.StartContext catalogQueryLanguageParser_StartContext0 = new CatalogQueryLanguageParser.StartContext(graphqlParser_ObjectValueContext0, (-1));
      Object object0 = catalogQueryLanguageBaseVisitor0.visitStart(catalogQueryLanguageParser_StartContext0);
      assertNull(object0);
  }
}
