/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 14:42:07 GMT 2019
 */

package org.ow2.proactive.catalog.util.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.ByteArrayInputStream;
import java.util.ArrayList;
import java.util.List;
import org.ow2.proactive.catalog.repository.entity.KeyValueLabelMetadataEntity;
import org.ow2.proactive.catalog.util.parser.CalendarDefinitionParser;

public class CalendarDefinitionParser_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CalendarDefinitionParser calendarDefinitionParser0 = new CalendarDefinitionParser();
      ArrayList<KeyValueLabelMetadataEntity> arrayList0 = new ArrayList<KeyValueLabelMetadataEntity>();
      String string0 = calendarDefinitionParser0.getIconPath(arrayList0);
      assertEquals("/automation-dashboard/styles/patterns/img/objects-icons/calendar_icon.png", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CalendarDefinitionParser calendarDefinitionParser0 = new CalendarDefinitionParser();
      byte[] byteArray0 = new byte[2];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      List<KeyValueLabelMetadataEntity> list0 = calendarDefinitionParser0.parse(byteArrayInputStream0);
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CalendarDefinitionParser calendarDefinitionParser0 = new CalendarDefinitionParser();
      boolean boolean0 = calendarDefinitionParser0.isMyKind("{l");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CalendarDefinitionParser calendarDefinitionParser0 = new CalendarDefinitionParser();
      // Undeclared exception!
      try { 
        calendarDefinitionParser0.isMyKind((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CalendarDefinitionParser calendarDefinitionParser0 = new CalendarDefinitionParser();
      byte[] byteArray0 = new byte[2];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      List<KeyValueLabelMetadataEntity> list0 = calendarDefinitionParser0.getMetadataKeyValues(byteArrayInputStream0);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CalendarDefinitionParser calendarDefinitionParser0 = new CalendarDefinitionParser();
      boolean boolean0 = calendarDefinitionParser0.isMyKind("calendarqe:s-");
      assertTrue(boolean0);
  }
}
