/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 14:35:06 GMT 2019
 */

package org.ow2.proactive.catalog.util.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import com.google.common.collect.ImmutableList;
import org.ow2.proactive.catalog.dto.Metadata;
import org.ow2.proactive.catalog.repository.entity.CatalogObjectRevisionEntity;
import org.ow2.proactive.catalog.repository.entity.KeyValueLabelMetadataEntity;
import org.ow2.proactive.catalog.util.parser.CatalogObjectParserResult;

public class CatalogObjectParserResult_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      KeyValueLabelMetadataEntity keyValueLabelMetadataEntity0 = new KeyValueLabelMetadataEntity();
      ImmutableList<KeyValueLabelMetadataEntity> immutableList0 = ImmutableList.of(keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0);
      CatalogObjectParserResult catalogObjectParserResult0 = new CatalogObjectParserResult("RO0Gx;hJ", "RO0Gx;hJ", (String) null, immutableList0);
      String string0 = catalogObjectParserResult0.getKind();
      assertEquals("RO0Gx;hJ", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ImmutableList<KeyValueLabelMetadataEntity> immutableList0 = ImmutableList.of();
      CatalogObjectParserResult catalogObjectParserResult0 = new CatalogObjectParserResult("", "", "", immutableList0);
      ImmutableList<KeyValueLabelMetadataEntity> immutableList1 = catalogObjectParserResult0.getKeyValueList();
      assertEquals(0, immutableList1.size());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ImmutableList<KeyValueLabelMetadataEntity> immutableList0 = ImmutableList.of();
      CatalogObjectParserResult catalogObjectParserResult0 = new CatalogObjectParserResult("", "", "", immutableList0);
      String string0 = catalogObjectParserResult0.getJobName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ImmutableList<KeyValueLabelMetadataEntity> immutableList0 = ImmutableList.of();
      CatalogObjectParserResult catalogObjectParserResult0 = new CatalogObjectParserResult("", "", "", immutableList0);
      String string0 = catalogObjectParserResult0.getProjectName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CatalogObjectParserResult catalogObjectParserResult0 = null;
      try {
        catalogObjectParserResult0 = new CatalogObjectParserResult("VRfg[+", "VRfg[+", "VRfg[+", (ImmutableList<KeyValueLabelMetadataEntity>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      KeyValueLabelMetadataEntity keyValueLabelMetadataEntity0 = new KeyValueLabelMetadataEntity();
      ImmutableList<KeyValueLabelMetadataEntity> immutableList0 = ImmutableList.of(keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0);
      CatalogObjectParserResult catalogObjectParserResult0 = new CatalogObjectParserResult("", "t", "t", immutableList0);
      String string0 = catalogObjectParserResult0.getJobName();
      assertEquals("", catalogObjectParserResult0.getKind());
      assertEquals("t", string0);
      assertEquals("t", catalogObjectParserResult0.getProjectName());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Long long0 = new Long(2L);
      CatalogObjectRevisionEntity catalogObjectRevisionEntity0 = new CatalogObjectRevisionEntity();
      KeyValueLabelMetadataEntity keyValueLabelMetadataEntity0 = new KeyValueLabelMetadataEntity(long0, "ZBZ{p[Z4+ns;", "!", "!", catalogObjectRevisionEntity0);
      ImmutableList<KeyValueLabelMetadataEntity> immutableList0 = ImmutableList.of(keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0);
      CatalogObjectParserResult catalogObjectParserResult0 = new CatalogObjectParserResult((String) null, "ZBZ{p[Z4+ns;", (String) null, immutableList0);
      String string0 = catalogObjectParserResult0.getJobName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Long long0 = Long.valueOf((-9223372036854775808L));
      CatalogObjectRevisionEntity catalogObjectRevisionEntity0 = new CatalogObjectRevisionEntity();
      KeyValueLabelMetadataEntity keyValueLabelMetadataEntity0 = new KeyValueLabelMetadataEntity(long0, "CharMatcher.invisible()", "U!gq5~#({", (String) null, catalogObjectRevisionEntity0);
      ImmutableList<KeyValueLabelMetadataEntity> immutableList0 = ImmutableList.of(keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0);
      CatalogObjectParserResult catalogObjectParserResult0 = new CatalogObjectParserResult("", "CharMatcher.invisible()", "CharMatcher.invisible()", immutableList0);
      String string0 = catalogObjectParserResult0.getKind();
      assertEquals("", string0);
      assertEquals("CharMatcher.invisible()", catalogObjectParserResult0.getProjectName());
      assertEquals("CharMatcher.invisible()", catalogObjectParserResult0.getJobName());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Long long0 = Long.valueOf((-9223372036854775808L));
      CatalogObjectRevisionEntity catalogObjectRevisionEntity0 = new CatalogObjectRevisionEntity();
      KeyValueLabelMetadataEntity keyValueLabelMetadataEntity0 = new KeyValueLabelMetadataEntity(long0, "CharMatcher.invisible()", "U!gq5~#({", (String) null, catalogObjectRevisionEntity0);
      ImmutableList<KeyValueLabelMetadataEntity> immutableList0 = ImmutableList.of(keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0);
      CatalogObjectParserResult catalogObjectParserResult0 = new CatalogObjectParserResult((String) null, (String) null, (String) null, immutableList0);
      String string0 = catalogObjectParserResult0.getKind();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Metadata metadata0 = new Metadata();
      KeyValueLabelMetadataEntity keyValueLabelMetadataEntity0 = new KeyValueLabelMetadataEntity(metadata0);
      ImmutableList<KeyValueLabelMetadataEntity> immutableList0 = ImmutableList.of(keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0);
      CatalogObjectParserResult catalogObjectParserResult0 = new CatalogObjectParserResult("R}MVVFv_kGH", "R}MVVFv_kGH", "R}MVVFv_kGH", immutableList0);
      String string0 = catalogObjectParserResult0.getProjectName();
      assertEquals("R}MVVFv_kGH", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Long long0 = Long.valueOf((-9223372036854775808L));
      CatalogObjectRevisionEntity catalogObjectRevisionEntity0 = new CatalogObjectRevisionEntity();
      KeyValueLabelMetadataEntity keyValueLabelMetadataEntity0 = new KeyValueLabelMetadataEntity(long0, "CharMatcher.invisible()", "U!gq5~#({", (String) null, catalogObjectRevisionEntity0);
      ImmutableList<KeyValueLabelMetadataEntity> immutableList0 = ImmutableList.of(keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0, keyValueLabelMetadataEntity0);
      CatalogObjectParserResult catalogObjectParserResult0 = new CatalogObjectParserResult((String) null, (String) null, (String) null, immutableList0);
      String string0 = catalogObjectParserResult0.getProjectName();
      assertNull(string0);
  }
}
