/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 14:36:18 GMT 2019
 */

package org.ow2.proactive.catalog.util.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.PipedInputStream;
import java.util.List;
import java.util.Vector;
import org.ow2.proactive.catalog.repository.entity.KeyValueLabelMetadataEntity;
import org.ow2.proactive.catalog.util.parser.NodeSourceParser;

public class NodeSourceParser_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NodeSourceParser nodeSourceParser0 = new NodeSourceParser();
      Vector<KeyValueLabelMetadataEntity> vector0 = new Vector<KeyValueLabelMetadataEntity>();
      String string0 = nodeSourceParser0.getIconPath(vector0);
      assertEquals("/automation-dashboard/styles/patterns/img/objects-icons/node_source_icon.png", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NodeSourceParser nodeSourceParser0 = new NodeSourceParser();
      boolean boolean0 = nodeSourceParser0.isMyKind("nodesource?");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NodeSourceParser nodeSourceParser0 = new NodeSourceParser();
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      List<KeyValueLabelMetadataEntity> list0 = nodeSourceParser0.getMetadataKeyValues(pipedInputStream0);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NodeSourceParser nodeSourceParser0 = new NodeSourceParser();
      // Undeclared exception!
      try { 
        nodeSourceParser0.isMyKind((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NodeSourceParser nodeSourceParser0 = new NodeSourceParser();
      boolean boolean0 = nodeSourceParser0.isMyKind("(6(j2(D");
      assertFalse(boolean0);
  }
}
