/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 14:37:25 GMT 2019
 */

package org.ow2.proactive.catalog.util.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.util.parser.SupportedParserKinds;

public class SupportedParserKinds_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SupportedParserKinds supportedParserKinds0 = SupportedParserKinds.POLICY;
      String string0 = supportedParserKinds0.toString();
      assertEquals("policynodesource", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SupportedParserKinds supportedParserKinds0 = SupportedParserKinds.WORKFLOW;
      String string0 = supportedParserKinds0.getDefaultIcon();
      assertEquals("/automation-dashboard/styles/patterns/img/wf-icons/wf-default-icon.png", string0);
  }
}
