/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 16:14:14 GMT 2019
 */

package org.ow2.proactive.catalog.service;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.service.BucketServiceTest;

public class BucketServiceTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BucketServiceTest bucketServiceTest0 = new BucketServiceTest();
  }
}
