/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 16:13:05 GMT 2019
 */

package org.ow2.proactive.catalog.service;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.service.CatalogObjectCallGraphServiceTest;

public class CatalogObjectCallGraphServiceTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CatalogObjectCallGraphServiceTest catalogObjectCallGraphServiceTest0 = new CatalogObjectCallGraphServiceTest();
  }
}
