/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 14:50:53 GMT 2019
 */

package org.ow2.proactive.catalog.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.ow2.proactive.catalog.report.CatalogObjectReportPDFGenerator;
import org.ow2.proactive.catalog.service.CatalogObjectReportService;
import org.ow2.proactive.catalog.service.CatalogObjectService;

public class CatalogObjectReportService_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CatalogObjectReportService catalogObjectReportService0 = new CatalogObjectReportService();
      CatalogObjectReportPDFGenerator catalogObjectReportPDFGenerator0 = mock(CatalogObjectReportPDFGenerator.class, new ViolatedAssumptionAnswer());
      Injector.inject(catalogObjectReportService0, (Class<?>) CatalogObjectReportService.class, "catalogObjectReportPDFGenerator", (Object) catalogObjectReportPDFGenerator0);
      CatalogObjectService catalogObjectService0 = mock(CatalogObjectService.class, new ViolatedAssumptionAnswer());
      Injector.inject(catalogObjectReportService0, (Class<?>) CatalogObjectReportService.class, "catalogObjectService", (Object) catalogObjectService0);
      Injector.validateBean(catalogObjectReportService0, (Class<?>) CatalogObjectReportService.class);
  }
}
