/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 16:01:37 GMT 2019
 */

package org.ow2.proactive.catalog.service;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.service.CatalogObjectReportServiceTest;

public class CatalogObjectReportServiceTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CatalogObjectReportServiceTest catalogObjectReportServiceTest0 = new CatalogObjectReportServiceTest();
  }
}
