/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 16:00:28 GMT 2019
 */

package org.ow2.proactive.catalog.service;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.service.CatalogObjectServiceTest;

public class CatalogObjectServiceTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CatalogObjectServiceTest catalogObjectServiceTest0 = new CatalogObjectServiceTest();
      assertEquals(1551960076669L, CatalogObjectServiceTest.REVISION_COMMIT_TIME);
  }
}
