/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 16:05:02 GMT 2019
 */

package org.ow2.proactive.catalog.service;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.service.GroupsWithPrefixRetrieverTest;

public class GroupsWithPrefixRetrieverTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GroupsWithPrefixRetrieverTest groupsWithPrefixRetrieverTest0 = new GroupsWithPrefixRetrieverTest();
  }
}
