/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 16:10:49 GMT 2019
 */

package org.ow2.proactive.catalog.service;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.service.OwnerGroupStringHelperTest;

public class OwnerGroupStringHelperTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OwnerGroupStringHelperTest ownerGroupStringHelperTest0 = new OwnerGroupStringHelperTest();
  }
}
