/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:12:21 GMT 2019
 */

package org.ow2.proactive.catalog.service;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import java.util.Stack;
import java.util.Vector;
import org.ow2.proactive.catalog.service.OwnerGroupStringHelper;

public class OwnerGroupStringHelper_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OwnerGroupStringHelper ownerGroupStringHelper0 = new OwnerGroupStringHelper();
      Vector<String> vector0 = new Vector<String>(0, 0);
      List<String> list0 = ownerGroupStringHelper0.getGroupsWithPrefixFromGroupList(vector0);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      OwnerGroupStringHelper ownerGroupStringHelper0 = new OwnerGroupStringHelper();
      Stack<String> stack0 = new Stack<String>();
      stack0.add("Lveg*R");
      List<String> list0 = ownerGroupStringHelper0.getGroupsWithPrefixFromGroupList(stack0);
      assertFalse(list0.contains("Lveg*R"));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      OwnerGroupStringHelper ownerGroupStringHelper0 = new OwnerGroupStringHelper();
      String string0 = ownerGroupStringHelper0.extractGroupFromBucketOwnerOrGroupString("Tc,SD");
      assertEquals("Tc,SD", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      OwnerGroupStringHelper ownerGroupStringHelper0 = new OwnerGroupStringHelper();
      String string0 = ownerGroupStringHelper0.extractGroupFromBucketOwnerOrGroupString("GROUP:");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      OwnerGroupStringHelper ownerGroupStringHelper0 = new OwnerGroupStringHelper();
      // Undeclared exception!
      try { 
        ownerGroupStringHelper0.extractGroupFromBucketOwnerOrGroupString((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      OwnerGroupStringHelper ownerGroupStringHelper0 = new OwnerGroupStringHelper();
      // Undeclared exception!
      try { 
        ownerGroupStringHelper0.getGroupsWithPrefixFromGroupList((List<String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
