/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 16:09:42 GMT 2019
 */

package org.ow2.proactive.catalog.service;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.service.RestApiAccessServiceTest;

public class RestApiAccessServiceTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RestApiAccessServiceTest restApiAccessServiceTest0 = new RestApiAccessServiceTest();
  }
}
