/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 16:02:45 GMT 2019
 */

package org.ow2.proactive.catalog.service;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.service.WorkflowXmlManipulatorTest;

public class WorkflowXmlManipulatorTest_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WorkflowXmlManipulatorTest workflowXmlManipulatorTest0 = new WorkflowXmlManipulatorTest();
  }
}
